### ISSUE TITLE
Bug: Typo on `Edit Status Page` 

### ISSUE THREAD

**Issue by TheDoubleH** [OneUptime/oneuptime#1050]
**Describe the bug**
When going to the 'Status Page' -> '</> HTML, CSS & JacaScript', -> 'Custom JavaScript' the intro-text says 

"Status Page Custom JavaScript. **Thsi** runs when the status page is loaded."
should be
"Status Page Custom JavaScript. **This** runs when the status page is loaded."

**To Reproduce**
See Above

**Expected behavior**
correct spelling

**Screenshots**
![image](https://github.com/OneUptime/oneuptime/assets/24259184/513a5b5d-f19e-4621-9e23-472b74bb1617)

**Deployment Type**
SaaS (at https://oneuptime.com)

**Additional context**
N/A

**Comment by simlarsen** [comment]
Fixed here: https://github.com/OneUptime/oneuptime/commit/74ee0f62245388b32db85a1c928b60c27be28908
