### ISSUE TITLE
Bug: Can't view API Key

### ISSUE THREAD

**Issue by mdymel** [OneUptime/oneuptime#1061]
**Describe the bug**
I have created a new API key, but can't display it. When I click on the button, it displays an empty page

**To Reproduce**
1. Go to 'API Keys'
2. Click on 'View API Key'
3. See empty page

**Expected behavior**
A way to view API Key

**Desktop (please complete the following information):**
 - OS: mac
 - Browser chrome
 - Version 119

**Deployment Type**
oneuptime.com

**Comment by simlarsen** [comment]
Fixed here: https://github.com/OneUptime/oneuptime/commit/4825e57821657b96b672a1df5d5bdca95c49c239 

Will be released today.
