### ISSUE TITLE
Enhancement: Better install docs.

### ISSUE THREAD

**Issue by CodeMeZone** [OneUptime/oneuptime#1079]
**Is your feature request related to a problem? Please describe.**
Docker install isn't complete.

**Describe the solution you'd like**
Set up a proxy to work with OneUptime, any DNS setups etc.

**Comment by CodeMeZone** [comment]
Anything help with this?

**Comment by simlarsen** [comment]
I believe all you need to do is set an A record to the IP address of the server and OneUptime should start working. Is there anything specific you're looking for?

**Comment by CodeMeZone** [comment]
> I believe all you need to do is set an A record to the IP address of the server and OneUptime should start working. Is there anything specific you're looking for?

SSL won't work.

**Comment by simlarsen** [comment]
@CodeMeZone Will add more docs.

**Comment by TheBinaryLoop** [comment]
Have you already updated the docs? I have the same problem

**Comment by iiTranquility** [comment]
I'd love to see this too. I followed both install guides but the result is extremely scuffed.

**Comment by kbekus** [comment]
It'd be great to have documentation around self hosting this behind a reverse proxy.  

1. How name resolution should work on the OneUptime host and the internal network
2. How to configure the config.env, particularly HOST= and HTTP_PROTOCOL=
3. How to configure Nginx, Apache or other to reverse proxy
4. How this is architected? Does the web browser client only talk to the ingress container or does it talk to all containers?
5. Do each of the containers talk to each other? How do they resolve names? Does each container need an FQDN?

**Comment by simlarsen** [comment]
Kubernetes Install: https://youtu.be/Ho5WyPHExTU
Docker Compose Install: https://youtu.be/j1SWmMW2oL4
