### ISSUE TITLE
Bug: "On Update Scheduled Maintenance Event" trigger works more than once

### ISSUE THREAD

**Issue by koroglumert** [OneUptime/oneuptime#1113]
**Describe the bug**
"On Update Scheduled Maintenance Event" trigger works more than once. It works 2 times when "Scheduled Maintenance Status" becomes "Ongoing". 
It works 3 times when it becomes "Ended". These works are happening at the same time.
The same error is also experienced in the "On Update Incident" trigger.

**To Reproduce**
1. Create a new worflow.
2. Add "On Update Scheduled Maintenance Event" as a trigger.
3. Adding Component does not affect this situation.
4. When the Scheduled Maintenance state value changes, examine the run&logs section of the worflow you created.
5. You can observe that workflow runs more than once for "Ongoing" and "Ended" state.

**Expected behavior**
I expect worflow to run once for each state change.

**Screenshots**
The workflow I created (I also tried with Component added)
![image](https://github.com/OneUptime/oneuptime/assets/83726007/e9033302-8645-4a81-8f49-a963b321f53e)

Scheduled Maintenance states
![image](https://github.com/OneUptime/oneuptime/assets/83726007/f0409440-e6fd-46db-8e7f-9b5aea284eac)

Run&Logs section and errors
![image](https://github.com/OneUptime/oneuptime/assets/83726007/6458ecfd-d5e4-488c-9edc-b469dd1bf440)

**Desktop (please complete the following information):**
 - OS: MACOS 14.0
 - Browser: chrome
 - Version release, after Commits on Jan 12, 2024

**Deployment Type**
Is this issue on  my server? 

**Additional context**

**Comment by simlarsen** [comment]
There are multiple fields in scheduled event being updated on the backend. Please add "Listen On" to your trigger component to trigger only on fields which are being updated.

**Comment by koroglumert** [comment]
The bug persists. In this case, the workflow runs 2 times with a single update. As I gave in the example picture;

Listen on:
`{
    "currentScheduledMaintenanceStateId": true
}
`

1. update
`"data":{"_id":"5bad991d-f36f-4d1c-8f97-5b2617658032","miscData":{"updatedFields":{"currentScheduledMaintenanceStateId":"b8a72ab3-0648-47e7-9ed1-7bbb8805be42"}}}}`

2. update
`"miscData":{"updatedFields":{"currentScheduledMaintenanceStateId":{"_type":"ObjectID","value":"b8a72ab3-0648-47e7-9ed1-7bbb8805be42"}}}}}`


<img width="371" alt="image" src="https://github.com/OneUptime/oneuptime/assets/83726007/f69c181d-2384-42c4-8bb9-b925ea48b384">

<img width="1083" alt="Ekran Resmi 2024-01-27 21 59 47" src="https://github.com/OneUptime/oneuptime/assets/83726007/02e9e7cb-3f37-4c3b-a10b-55f291271e50">

<img width="1079" alt="Ekran Resmi 2024-01-27 21 59 33" src="https://github.com/OneUptime/oneuptime/assets/83726007/75418f0a-4b29-4547-8f98-3817210a9a64">

**Comment by koroglumert** [comment]
Btw if I change the state manually, this error does not occur. 

"miscData":{"updatedFields":{"currentScheduledMaintenanceStateId":{"_type":"ObjectID","value":"2daad04f-77b9-4280-aa12-b930c8296ff4"}}}}}

I clicked on this
<img width="245" alt="Ekran Resmi 2024-01-27 22 09 37" src="https://github.com/OneUptime/oneuptime/assets/83726007/1a7df07b-784f-44ee-a339-d6f36e7c8f6a">

<img width="1166" alt="Ekran Resmi 2024-01-27 22 10 07" src="https://github.com/OneUptime/oneuptime/assets/83726007/40343556-9d11-46ba-b160-4ac80218aeaf">

**Comment by simlarsen** [comment]
@koroglumert let me investigate and get back.

**Comment by koroglumert** [comment]
@simlarsen Hey Simon, I've entered some new bugs. It's a great app, I've noted the details I can see while I'm trying to learn it. I'm very interested in the Workflow part. I would like to support new users with a blog post as we progress on this.

**Comment by xuebingli** [comment]
I'm taking a look and will share what I find here.

**Comment by xuebingli** [comment]
I believe I've figured out the cause. I'll submit a PR in the next day or two.
