### ISSUE TITLE
Bug: cannot access admin features

### ISSUE THREAD

**Issue by JesseWebDotCom** [OneUptime/oneuptime#1115]
V7.0.977 - i only have one user account on the entire server. If I try to go to /admin or /accounts, I immediately get redirected to my project page.  On /admin, the page shows for a split second and says something like I'm not authorized.

**Comment by JesseWebDotCom** [comment]
How do I toggle the isMasterAdmin property for my user account in the database?

**Comment by simlarsen** [comment]
Flip `isMaterAdmin` in Users Table for that user. Log out and log back in.
