### ISSUE TITLE
Bug: On Update Incident trigger isn't working when the incident state value is changed

### ISSUE THREAD

**Issue by koroglumert** [OneUptime/oneuptime#1119]
**Describe the bug**
"On Update Incident" trigger does not work when the current value of the incident is changed without using the "edit incident" button (ex: Acknowledge Incident). 
!! This is only valid when the "listen on" field is filled in the trigger value

**To Reproduce**
1. Set up a workflow with "On Update Incident" trigger
2. Go to an "Identified" incident
3. Click on "Acknowledge Incident"
4. Workflow did not work even though Incident was updated. Workflow works only when "edit incident" button is used.

**Expected behavior**
When ı click on "Acknowledge Incident" I expect the trigger to run on "Update Event"

**Screenshots**
Our workflow with  "On Update Incident" trigger
<img width="1406" alt="Ekran Resmi 2024-01-24 13 28 17" src="https://github.com/OneUptime/oneuptime/assets/83726007/c207c5d7-fa8e-4da3-858f-f4ec21d365e6">

Our trigger inside
<img width="379" alt="Ekran Resmi 2024-01-24 13 47 12" src="https://github.com/OneUptime/oneuptime/assets/83726007/f408cf9e-218b-4c8d-a1dd-3b94228e16d3">

Our "Identified" incident
<img width="1024" alt="Ekran Resmi 2024-01-24 13 28 51" src="https://github.com/OneUptime/oneuptime/assets/83726007/47ca774f-0181-49ce-8e6f-c2f8d681eb86">

 When we click on "Acknowledge Incident"
 
<img width="1010" alt="Ekran Resmi 2024-01-24 13 29 01" src="https://github.com/OneUptime/oneuptime/assets/83726007/cb565f7d-68b3-4050-8577-32c8ce88474e">

Workflow did not work even though Incident was updated

**Desktop (please complete the following information):**
OS: MACOS 14.0
Browser: chrome
Version release, after Commits on Jan 12, 2024

**Smartphone (please complete the following information):**

**Deployment Type**
Is this issue on my server

**Additional context**

I think that the Workflow section is the biggest area of freedom in the system, and I believe that it needs to be improved in terms of user experience.

**Comment by simlarsen** [comment]
Can you please change Listen on to: 

```
{
   "title": true
}
```

and it should work. Please reopen if it still does not work

**Comment by koroglumert** [comment]
Thank you for your interest. 
As a small test note:
It works when I use "currentIncidentStateId" but not when I use "currentIncidentState entity name".

<img width="302" alt="Ekran Resmi 2024-01-27 19 22 05" src="https://github.com/OneUptime/oneuptime/assets/83726007/259d2137-15f6-4d51-bd0e-de457bd43071">

<img width="259" alt="Ekran Resmi 2024-01-27 19 22 47" src="https://github.com/OneUptime/oneuptime/assets/83726007/ff7e71e3-a066-4fe9-9c88-16861a80de1e">
