### ISSUE TITLE
Troubleshooting HelmChart installation

### ISSUE THREAD

**Issue by jiglesia3** [OneUptime/oneuptime#1175]
Hi, I've attempted to install/deploy the latest version of the Helm chart, but quite a few of the pods are in a constant state of recreating themselves. I don't have any logs for those pods since they go into a Running state, and then back to ContainerCreating after a few seconds with no distinct errors. The database pods are running consistently and ready to accept connections according to the logs, but again, no error logs. Any insights?

**Comment by simlarsen** [comment]
Did you resolve this?

**Comment by jiglesia3** [comment]
Sorry, it ended up being related to this other issue I submitted. https://github.com/OneUptime/oneuptime/issues/1176
