### ISSUE TITLE
Enhancement: Modify Dockerfiles to run as nonroot / non-root user

### ISSUE THREAD

**Issue by jiglesia3** [OneUptime/oneuptime#1176]
**Is your feature request related to a problem? Please describe.**
Each container in the helm chart installation currently runs as root, which violates security policies we have in place on our clusters. We'd like to request enhancing OneUptime's security posture by following best practice and adding a nonroot / non-root user to each Dockerfile. 

**Describe the solution you'd like**
Add a nonroot user to each Dockerfile.tpl, similar to this alpine linux [gist](https://gist.github.com/avishayp/33fcee06ee440524d21600e2e817b6b7?permalink_comment_id=4348706). Modify files and permissions from npm installs as necessary. 

**Describe alternatives you've considered**
The only alternative is leaving the Dockerfiles as-is. 

**Additional context**
Since this project has bitnami image dependencies, 
https://docs.bitnami.com/tutorials/why-non-root-containers-are-important-for-security

**Comment by simlarsen** [comment]
@jiglesia3 Let me look into this and hopefully have this fixed.

**Comment by simlarsen** [comment]
This is complete. Please update your helm chart and you'll have new images.

**Comment by simlarsen** [comment]
This is the commit: https://github.com/OneUptime/oneuptime/commit/519daba29490333246b729d82952ab8c8b6b8e66
