### ISSUE TITLE
npm start returns docker error

### ISSUE THREAD

**Issue by kisonay** [OneUptime/oneuptime#1196]
**Describe the bug**
Trying to run a hobby install for the first time and recieve the following error:

``` 

root@oneuptime:/oneuptime# npm start

> app@3.0.2 start
> export $(grep -v '^#' config.env | xargs) && docker compose up --remove-orphans -d $npm_config_services && npm run status-check

service "status-page" can't be used with `extends` as it declare `depends_on`
```

**Versions**

```
root@oneuptime:/oneuptime# docker -v
Docker version 25.0.3, build 4debf41
root@oneuptime:/oneuptime# node -v
v18.19.0
root@oneuptime:/oneuptime# npm -v
9.2.0
```

**Deployment Type**
self hosted

**Additional context**
the error seems to jump between services, sometimes app service produces the error, sometimes ingestor, etc.

**Comment by simlarsen** [comment]
Not sure what's causing this but we have removed dependencies between services in the lastest update so this should now be fixed. Can you please fetch the latest repo and try again? Please re-open this issue if this is not resolved.
