### ISSUE TITLE
Bug: Workflow Variable Form requires an optional field (Secret)

### ISSUE THREAD

**Issue by DonSYS91** [OneUptime/oneuptime#1202]
Workflow Variable form is forcing the "Secret" field which logically should be optional.
Cloud customer here not self-hosted

**Comment by simlarsen** [comment]
Fixed here: https://github.com/OneUptime/oneuptime/commit/b47dd5656d77f3bb2287a5159322275d08df6ac1 

Thank you for reporting. 

Wil be released in few days.
