### ISSUE TITLE
Prometheus integration?

### ISSUE THREAD

**Issue by davejhahn** [OneUptime/oneuptime#1271]
**Describe the bug**
This isn't really a bug, but since there may already be capability, I'm not sure it is a feature request.  Looking for some guidance in how to integrate Prometheus.

I already have Prometheus that has extensive rules and alerts and would like to push those into Oneuptime to have a polished control around it, use teams, escalations, etc...

Not really sure how this would be done other than creating an intermediate app that Prometheus calls via a webhook which then does whatever it does to make the API call to create the incident in oneuptime with the appropriate structure.

Unless I'm missing integrations somewhere.  Seems like this would be a really common use case.

Also not clear on pushing notifications out--looks like there is just SMS, Phone, and Email.  We would never use that as a primary way for sending alerts, ideally there would be an app that whoever is on-call would receive the alert, but assuming there is not one, would like to push the alerts to  a MS Teams channel.  Is there any integration for Teams or Slack or even a general API endpoint?

Looks really good, but I have no idea how to integrate it with what I would consider basic foundational services.

Looking for some guidance.

Thanks!

**Comment by simlarsen** [comment]
We have a feature called workflows that lets you integrate OneUptime with anything. Here is the link to learn more: https://www.youtube.com/watch?v=z-b7_KQcUDY&ab_channel=OneUptime 

Feel free to re-open this issue if you need more help.
