### ISSUE TITLE
Error : Cannot read properties of undefined (reading '_id')

### ISSUE THREAD

**Issue by Shrividhhya7** [OneUptime/oneuptime#1272]
**Describe the Error**
Cannot read properties of undefined (reading '_id').

**To Reproduce**
I have created a trigger on create incident as the below
![image](https://github.com/OneUptime/oneuptime/assets/147608536/9286569c-3630-4bad-982d-cd5bfef1e7f1)

Once the incident is created it should a notify in the microsoft teams channel as below. So i created a webhook and updated the webhook in the component as below.
![image](https://github.com/OneUptime/oneuptime/assets/147608536/11e1c368-283a-41b0-9356-0a87cc97633b)

However, when i create a incident, the trigger doesnt work and i when i run the workflow manually, i see the logs as below.

![image](https://github.com/OneUptime/oneuptime/assets/147608536/8585aa73-60e7-48bc-a732-fb151f6f53a1)

![image](https://github.com/OneUptime/oneuptime/assets/147608536/50e41e9e-33ea-419c-a506-4fa57c73c370)

** Expected **
I believe, the trigger will have to be executed and message should be posted in our teams channel.

**Comment by simlarsen** [comment]
I believe you're looking for `On Create Incident` component and not `On Create Incident State` component.
