### ISSUE TITLE
Error:  unable to send messages to Microsoft Teams Channel.

### ISSUE THREAD

**Issue by Shrividhhya7** [OneUptime/oneuptime#1279]
**Describe the bug**
One up Time is unable to send messages to the Microsoft Teams Channel.

I have created a webhook in Microsoft Teams and was trying to send messages to a channel in Teams, the configuration is as below.

![image](https://github.com/OneUptime/oneuptime/assets/147608536/72bc802d-fdd1-49cf-ac01-4343de8e521d)

However, when I created the incident, it could read the message from the Slack component, but it was unable to send the message to the team's channel and received an error, more details are in the screenshot below.

Mar 22 2024, 05:40 GMT: {"error":"Server Error."}
Mar 22 2024, 05:40 GMT: Executing Port: Error
![image](https://github.com/OneUptime/oneuptime/assets/147608536/d9cd003a-d3db-414b-9a7e-ac9686be05ad)

**Expected behavior**
Microsoft Teams channel should receive the message from the One Up Time tool.

**Screenshots**
![image](https://github.com/OneUptime/oneuptime/assets/147608536/72bc802d-fdd1-49cf-ac01-4343de8e521d)

![image](https://github.com/OneUptime/oneuptime/assets/147608536/d9cd003a-d3db-414b-9a7e-ac9686be05ad)

**Comment by simlarsen** [comment]
Please use Teams component adn not slack component.

**Comment by Shrividhhya7** [comment]
I don't see any Teams component to send messages in OneUp Time. Could you please share any screenshots.

![image](https://github.com/OneUptime/oneuptime/assets/147608536/7235d54b-a6a0-41bf-a17b-71829d5d7354)

**Comment by simlarsen** [comment]
<img width="363" alt="image" src="https://github.com/OneUptime/oneuptime/assets/104437376/6cdadb00-8921-4255-b81b-556bb8d78589">

If you dont see it, you need to update your software to latest.
