### ISSUE TITLE
Bug: <"Error: Endpoint is not available">

### ISSUE THREAD

**Issue by kbekus** [OneUptime/oneuptime#1291]
**Describe the bug**
I'm just starting out with self hosting OneUptime and have followed the self hosting docker instructions. I've set up a reverse proxy using nginx proxy manager but when I connect to the instance and try to register a new account I get the error "Endpoint is not available".

![image](https://github.com/OneUptime/oneuptime/assets/99165155/88d81521-7390-495c-94a9-faf7c4c5ced1)

**To Reproduce**

I've set up a new Debian 12 environment in an LXC on Proxmox. Installed the latest docker engine from the the docker repo. Pulled the git repo of OneUptime, edited the config.env and tried to run the service. All the individual containers come up fine. I've tried to launch the containers both using npm start and export $(grep -v '^#' config.env | xargs) && docker compose up --remove-orphans -d

**Desktop (please complete the following information):**
 - OS: Debian 12
 - Latest (7.0.1830)

**Deployment Type**
Self hosted docker

**Additional context**
I've tried both Chrome and Edge as browsers.  The reverse proxy is handling SSL but onforwarding http only to OneUptime. I've tried HTTP_PROTOCOL both as http and https with the same result.  I'm not seeing any useful errors in the logs.

**Comment by simlarsen** [comment]
Looks like this is an issue with your HOST env var.

**Comment by kbekus** [comment]
thanks Simon,

can you tell me please whether I should set the HOST variable as localhost or the FQDN?  I'm assuming that the "Endpoint is not available" error is because one container can't talk to another container via a http request?

**Comment by simlarsen** [comment]
HOST should be FQDN.

**Comment by kbekus** [comment]
thanks Simon.  Just for closure I've got it running. If it helps anyone here are some pointers:

1. if you make changes to the config.env file make sure to docker compose rm the containers. Just stopping and starting them does not make them use the new settings.
2. I did not need an entry for the FQDN in /etc/hosts
3. in config.env I set HOST= the FQDN of the service as known when you access it from the outside world
4. in config.env I set HTTP_PROTOCOL=https
5. I use nginx proxy manager as a reverse proxy. It's set to use a LetsEncrypt certificate for this service so I also have a CNAME record in external DNS. npm is set to forward to http://internal.ip.address:80 . I also ticked websockets support and HTTP/2 support.

I'm looking forward to giving this a try. Thanks once again.

**Comment by motoridersd** [comment]
I'm having the same problem with the docker deployment.

I'm also using Nginx Proxy Manager with a wildcard certificate. I put the FQDN in config.env, and changed the HTTP_PROTOCOL to https, but I still have the same error.

When I try to create the account I get the same " Error: Endpoint is not available" as the OP.

I can't open https://ip_address, I get a Secure Connection Failed message, but I know the docker process is listening on port 443
