### ISSUE TITLE
Bug: More Details in Microsoft Teams Message

### ISSUE THREAD

**Issue by Shrividhhya7** [OneUptime/oneuptime#1307]
**Describe the bug**
Need to add more details in a Microsoft Teams message like link to the incident that was generated or posted to Microsoft Teams etc.

**To Reproduce**

**Expected behavior**
Need an option or a hyperlink to the alert that is generated.

**Screenshots**

Currently, the messages are being sent by One uptime as per the screenshot below, which is good. But we want to add more details in the alerts like link to the incident.
![image](https://github.com/OneUptime/oneuptime/assets/147608536/46c83e9a-8e55-4e61-9937-d088d795cf16)

However, we want a link to the incident that was generated in One uptime. Something like (it is just an example screenshot) like a hyperlink to the alert that was generated in Oneup TIme.
![image](https://github.com/OneUptime/oneuptime/assets/147608536/57b5d957-14b1-4c5b-b591-af18788310d6)

Please let us know , if you need more details.

**Comment by simlarsen** [comment]
You can import variables from the upstream components to get the details. Please let me know if this helps!
