### ISSUE TITLE
cannot watch any main page contents after installation in AKS

### ISSUE THREAD

**Issue by jeonck** [OneUptime/oneuptime#1317]
Environment:

Deployment Method: Helm
Kubernetes Service: Azure Kubernetes Service (AKS)
Storage Class: managed-csi

Issue Description:
After deploying OneUptime using Helm in my AKS cluster, I've encountered an issue preventing the proper functioning of the application. 

installed with helm in AKS
helm install oneuptime oneuptime/oneuptime -f d-oneuptime-observe.yaml -n observe

values.yaml -> rename:  d-oneuptime-observe.yaml 
`# host: 
# If hosted on non-ssl server then change this to http
httpProtocol: http 
global: 
  storageClass: managed-csi`

svc status 
![image](https://github.com/OneUptime/oneuptime/assets/11763994/d10fdcb2-5bf0-4895-83be-2a86ff727619)

pod status
![image](https://github.com/OneUptime/oneuptime/assets/11763994/5ff9f812-74b5-459a-b2e4-cd271adecf1a)

access web page -> but, cannot see any contents 
![image](https://github.com/OneUptime/oneuptime/assets/11763994/66f34da2-ccc2-4138-8a95-16ea452183b2)

pod log:

envsubst-on-templates.sh: Running auto_envsubst
envsubst-on-templates.sh: Running envsubst on /etc/nginx/templates/default.conf.template to /etc/nginx/conf.d/default.conf
2024/04/05 00:59:33 [warn] 18#18: the "listen ... http2" directive is deprecated, use the "http2" directive instead in /etc/nginx/conf.d/default.conf:42
nginx: [warn] the "listen ... http2" directive is deprecated, use the "http2" directive instead in /etc/nginx/conf.d/default.conf:42
2024/04/05 00:59:33 [warn] 18#18: the "listen ... http2" directive is deprecated, use the "http2" directive instead in /etc/nginx/conf.d/default.conf:82
nginx: [warn] the "listen ... http2" directive is deprecated, use the "http2" directive instead in /etc/nginx/conf.d/default.conf:82
2024/04/05 00:59:33 [warn] 18#18: protocol options redefined for 0.0.0.0:80 in /etc/nginx/conf.d/default.conf:117
nginx: [warn] protocol options redefined for 0.0.0.0:80 in /etc/nginx/conf.d/default.conf:117
2024/04/05 00:59:33 [warn] 18#18: the "listen ... http2" directive is deprecated, use the "http2" directive instead in /etc/nginx/conf.d/default.conf:326
nginx: [warn] the "listen ... http2" directive is deprecated, use the "http2" directive instead in /etc/nginx/conf.d/default.conf:326
2024/04/05 00:59:33 [warn] 18#18: protocol options redefined for 0.0.0.0:80 in /etc/nginx/conf.d/default.conf:326
nginx: [warn] protocol options redefined for 0.0.0.0:80 in /etc/nginx/conf.d/default.conf:326
2024/04/05 00:59:33 [warn] 18#18: conflicting server name "localhost" on 0.0.0.0:80, ignored
nginx: [warn] conflicting server name "localhost" on 0.0.0.0:80, ignored
2024/04/05 00:59:33 [notice] 18#18: using the "epoll" event method
2024/04/05 00:59:33 [notice] 18#18: nginx/1.25.4
2024/04/05 00:59:33 [notice] 18#18: built by gcc 12.2.1 20220924 (Alpine 12.2.1_git20220924-r10)
2024/04/05 00:59:33 [notice] 18#18: OS: Linux 5.15.0-1058-azure
2024/04/05 00:59:33 [notice] 18#18: getrlimit(RLIMIT_NOFILE): 1048576:1048576
2024/04/05 00:59:33 [notice] 18#18: start worker processes
2024/04/05 00:59:33 [notice] 18#18: start worker process 26
2024/04/05 00:59:33 [notice] 18#18: start worker process 27
2024/04/05 00:59:33 [notice] 18#18: start worker process 28
2024/04/05 00:59:33 [notice] 18#18: start worker process 29

> @oneuptime/nginx@1.0.0 start
> node --require ts-node/register Index.ts

{
  timestamp: 1712278818411000,
  traceId: undefined,
  spanId: undefined,
  traceFlags: undefined,
  severityText: undefined,
  severityNumber: 9,
  body: 'App Version: 7.0.1924',
  attributes: {}
}
....
....
....
2024/04/05 01:45:11 [warn] 85#85: *2035 using uninitialized "billing_enabled" variable, client: 10.25.0.10, server: _, request: "GET /status-page/:statusPageId HTTP/1.1", host: "4.230.149.30"
10.25.0.10 - - [05/Apr/2024:01:45:11 +0000] "GET /status-page/:statusPageId HTTP/1.1" 304 0 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:124.0) Gecko/20100101 Firefox/124.0" "-"
2024/04/05 01:45:11 [warn] 85#85: *2037 using uninitialized "billing_enabled" variable, client: 10.25.0.10, server: _, request: "GET /status-page/env.js HTTP/1.1", host: "4.230.149.30", referrer: "http://4.230.149.30/status-page/:statusPageId"
2024/04/05 01:45:11 [warn] 85#85: *2035 using uninitialized "billing_enabled" variable, client: 10.25.0.10, server: _, request: "GET /status-page/assets/fonts/camphor/font2.woff2 HTTP/1.1", host: "4.230.149.30", referrer: "http://4.230.149.30/status-page/:statusPageId"
2024/04/05 01:45:11 [warn] 85#85: *2038 using uninitialized "billing_enabled" variable, client: 10.25.0.59, server: _, request: "GET /status-page/assets/fonts/camphor/font1.woff2 HTTP/1.1", host: "4.230.149.30", referrer: "http://4.230.149.30/status-page/:statusPageId"
10.25.0.10 - - [05/Apr/2024:01:45:11 +0000] "GET /status-page/env.js HTTP/1.1" 200 2628 "http://4.230.149.30/status-page/:statusPageId" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:124.0) Gecko/20100101 Firefox/124.0" "-"
10.25.0.10 - - [05/Apr/2024:01:45:11 +0000] "GET /status-page/assets/fonts/camphor/font2.woff2 HTTP/1.1" 304 0 "http://4.230.149.30/status-page/:statusPageId" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:124.0) Gecko/20100101 Firefox/124.0" "-"
10.25.0.59 - - [05/Apr/2024:01:45:11 +0000] "GET /status-page/assets/fonts/camphor/font1.woff2 HTTP/1.1" 304 0 "http://4.230.149.30/status-page/:statusPageId" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:124.0) Gecko/20100101 Firefox/124.0" "-"
2024/04/05 01:45:11 [warn] 85#85: *2042 using uninitialized "billing_enabled" variable, client: 10.25.0.10, server: _, request: "GET /status-page/assets/fonts/camphor/font3.woff2 HTTP/1.1", host: "4.230.149.30", referrer: "http://4.230.149.30/status-page/:statusPageId"
10.25.0.10 - - [05/Apr/2024:01:45:11 +0000] "GET /status-page/assets/fonts/camphor/font3.woff2 HTTP/1.1" 304 0 "http://4.230.149.30/status-page/:statusPageId" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:124.0) Gecko/20100101 Firefox/124.0" "-"
2024/04/05 01:45:11 [warn] 85#85: *2037 using uninitialized "billing_enabled" variable, client: 10.25.0.10, server: _, request: "GET /status-page/assets/fonts/camphor/font4.woff2 HTTP/1.1", host: "4.230.149.30", referrer: "http://4.230.149.30/status-page/:statusPageId"
2024/04/05 01:45:11 [warn] 85#85: *2044 using uninitialized "billing_enabled" variable, client: 10.25.0.10, server: _, request: "GET /status-page/dist/bundle.js HTTP/1.1", host: "4.230.149.30", referrer: "http://4.230.149.30/status-page/:statusPageId"
10.25.0.10 - - [05/Apr/2024:01:45:11 +0000] "GET /status-page/assets/fonts/camphor/font4.woff2 HTTP/1.1" 304 0 "http://4.230.149.30/status-page/:statusPageId" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:124.0) Gecko/20100101 Firefox/124.0" "-"
10.25.0.10 - - [05/Apr/2024:01:45:11 +0000] "GET /status-page/dist/bundle.js HTTP/1.1" 304 0 "http://4.230.149.30/status-page/:statusPageId" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:124.0) Gecko/20100101 Firefox/124.0" "-"
10.25.0.10 - - [05/Apr/2024:01:45:11 +0000] "POST /status-page-api/master-page/:statusPageId HTTP/1.1" 500 24 "http://4.230.149.30/status-page/:statusPageId" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:124.0) Gecko/20100101 Firefox/124.0" "-"
2024/04/05 01:48:20 [error] 86#86: *2173 cannot load certificate "/etc/nginx/certs/StatusPageCerts/.crt": BIO_new_file() failed (SSL: error:80000002:system library::No such file or directory:calling fopen(/etc/nginx/certs/StatusPageCerts/.crt, r) error:10000080:BIO routines::no such file) while SSL handshaking, client: 10.25.0.10, server: 0.0.0.0:443
2024/04/05 01:49:07 [error] 87#87: *2206 cannot load certificate "/etc/nginx/certs/StatusPageCerts/.crt": BIO_new_file() failed (SSL: error:80000002:system library::No such file or directory:calling fopen(/etc/nginx/certs/StatusPageCerts/.crt, r) error:10000080:BIO routines::no such file) while SSL handshaking, client: 10.25.0.59, server: 0.0.0.0:443
2024/04/05 01:49:54 [warn] 87#87: *2239 using uninitialized "billing_enabled" variable, client: 10.25.0.10, server: _, request: "GET /status-page/:statusPageId HTTP/1.1", host: "4.230.149.30"
2024/04/05 01:49:54 [warn] 87#87: *2240 using uninitialized "billing_enabled" variable, client: 10.25.0.10, server: _, request: "GET /status-page/env.js HTTP/1.1", host: "4.230.149.30"
10.25.0.10 - - [05/Apr/2024:01:49:54 +0000] "GET /status-page/env.js HTTP/1.1" 200 2628 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:124.0) Gecko/20100101 Firefox/124.0" "-"
10.25.0.10 - - [05/Apr/2024:01:49:54 +0000] "GET /status-page/:statusPageId HTTP/1.1" 200 1732 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:124.0) Gecko/20100101 Firefox/124.0" "-"
{
  timestamp: 1712281800827000,
  traceId: undefined,
  spanId: undefined,
  traceFlags: undefined,
  severityText: undefined,
  severityNumber: 9,
  body: 'Job StatusPageCerts:WriteSelfSignedCertsToDisk Start',
  attributes: {}
}
{
  timestamp: 1712281800841000,
  traceId: undefined,
  spanId: undefined,
  traceFlags: undefined,
  severityText: undefined,
  severityNumber: 9,
  body: 'Job StatusPageCerts:WriteSelfSignedCertsToDisk End',
  attributes: {}
}
2024/04/05 01:50:01 [warn] 87#87: *2247 using uninitialized "billing_enabled" variable, client: 10.25.0.10, server: _, request: "GET / HTTP/1.0"
10.25.0.10 - - [05/Apr/2024:01:50:01 +0000] "GET / HTTP/1.0" 200 4130 "-" "-" "-"
2024/04/05 01:50:01 [error] 85#85: *2250 cannot load certificate "/etc/nginx/certs/StatusPageCerts/.crt": BIO_new_file() failed (SSL: error:80000002:system library::No such file or directory:calling fopen(/etc/nginx/certs/StatusPageCerts/.crt, r) error:10000080:BIO routines::no such file) while SSL handshaking, client: 10.25.0.59, server: 0.0.0.0:443
10.25.0.59 - - [05/Apr/2024:01:52:00 +0000] "CONNECT www.google.com:443 HTTP/1.1" 400 157 "-" "-" "-"
{
  timestamp: 1712282100134000,
  traceId: undefined,
  spanId: undefined,
  traceFlags: undefined,
  severityText: undefined,
  severityNumber: 9,
  body: 'Job StatusPageCerts:WriteSelfSignedCertsToDisk Start',
  attributes: {}
}
{
  timestamp: 1712282100192000,
  traceId: undefined,
  spanId: undefined,
  traceFlags: undefined,
  severityText: undefined,
  severityNumber: 9,
  body: 'Job StatusPageCerts:WriteSelfSignedCertsToDisk End',
  attributes: {}
}
2024/04/05 01:57:47 [error] 86#86: *2563 cannot load certificate "/etc/nginx/certs/StatusPageCerts/.crt": BIO_new_file() failed (SSL: error:80000002:system library::No such file or directory:calling fopen(/etc/nginx/certs/StatusPageCerts/.crt, r) error:10000080:BIO routines::no such file) while SSL handshaking, client: 10.25.0.10, server: 0.0.0.0:443

**Comment by simlarsen** [comment]
Please specify correct `HOST` and `HTTP_PROTOCOL` value in values.yaml.
