### ISSUE TITLE
Bug: IPv6 Only Cluster fails to resolve svc.cluster.local addresses

### ISSUE THREAD

**Issue by xorl** [OneUptime/oneuptime#1348]
**Describe the bug**
When deployed on an IPv6 only cluster, the app pod cannot resolve svc.cluster.local addresses as it expects an A, not a AAAA.

Error: getaddrinfo ENOTFOUND platform-oneuptime-redis-master.oneuptime.svc.cluster.local
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:107:26)
    at GetAddrInfoReqWrap.callbackTrampoline (node:internal/async_hooks:130:17) {
  errno: -3007,
  code: 'ENOTFOUND',
  syscall: 'getaddrinfo',
  hostname: 'platform-oneuptime-redis-master.oneuptime.svc.cluster.local'
}

**To Reproduce**
1. Deploy iPv6 only cluster
2. Configure redis to bind on * and -::*
3. Restart -app pod.

**Expected behavior**
When deployed, service should be able to to resolve AAAA addresses.
Addresses obfuscated below.
```
➜  kubectl -n oneuptime exec -i -t dnsutils -- nslookup platform-oneuptime-redis-master.oneuptime.svc.cluster.local
Server:		<obfuscated>
Address:	<obfuscated>#53

*** Can't find platform-oneuptime-redis-master.oneuptime.svc.cluster.local: No answer

➜  kubectl -n oneuptime exec -i -t dnsutils -- nslookup -q=AAAA platform-oneuptime-redis-master.oneuptime.svc.cluster.local
Server:		<obfuscated>
Address:	<obfuscated>#53

platform-oneuptime-redis-master.oneuptime.svc.cluster.local	has AAAA address <obfuscated>
```

**Screenshots**

**Deployment Type**
self-hosted - EKS (kubernetes)

**Comment by xorl** [comment]
Looks like this might be related, https://github.com/mastodon/mastodon/issues/27043

**Comment by simlarsen** [comment]
Not sure if this will help but you can actually change this by setting:
```
global:
  clusterDomain: 
```

**Comment by xorl** [comment]
> Not sure if this will help but you can actually change this by setting:
> 
> ```
> global:
>   clusterDomain: 
> ```

I am not sure that will fix it either as the domain resolves (AAAA only since there is no IPv4 address to resolve)

**Comment by WillDaSilva** [comment]
@xorl Do you know if this issue is still occurring? I'm considering deploying into an IPv6 only cluster, and I'd rather not be blocked by this issue.

**Comment by JulesdeCube** [comment]
Hello and thanks you for this ammazing application. 

At this day it's still an issue and a deal breaker for me. 

Did you plan to fix this issue on the near future ?
