### ISSUE TITLE
Enhancement: incidents page - ability to delete incidents

### ISSUE THREAD

**Issue by JesseWebDotCom** [OneUptime/oneuptime#1392]
On the incidents page, there should be a way to:
1) delete individual incidents (ex. a "Delete Incident" button next to the "View Incident" button
2) multi select incidents (ex. a check boxes next to each incident, a "check all" button) and then a "Delete Incidents" button that deletes several incidents at once

**Comment by simlarsen** [comment]
<img width="2131" alt="image" src="https://github.com/OneUptime/oneuptime/assets/104437376/c337f6d9-b4ac-4c30-acd2-f24d1034bcc5">


This is done and complete.
