### ISSUE TITLE
Enhancement: FYI - Emojis work!

### ISSUE THREAD

**Issue by JesseWebDotCom** [OneUptime/oneuptime#1402]
Just wanted to let you know that emojis work in things like status page resource group names, monitor names, etc.  Useful for those of us who want to make the page a little more graphical/engaging.

To do this, I simply searched for an emoji on emojipedia.com, copied it, and pasted it in  the display name field.  This likely works on all text fields (but you'll need to validate).

Maybe you want to add this to documentation or include visually in one of your website images.

**Comment by simlarsen** [comment]
Yes OneUptime supports Unicode whcih uncludes emoji. I will let my marketing team know and they will update the website. 

Closing this issue.
