### ISSUE TITLE
GitHub Actions build job to run home tests

### ISSUE THREAD

**Issue by simlarsen** [OneUptime/oneuptime#142]
Please look at this file for inspiration: .github/workflows/test.common-server.yaml

We need kind of the same file to run home tests.

**Comment by Reneuwumuhire** [comment]
This ticket was handled by @bigelio  

reference

https://github.com/OneUptime/oneuptime/blob/6fe2f723ae238b473cf0a0ee2344590362a74c6e/.github/workflows/test.home.yaml

THIS TICKET HAS TO BE CLOSED.

**Comment by Reneuwumuhire** [comment]
Needs to be closed, Was handled in the previous PR.
