### ISSUE TITLE
Error: Status Page ID Not Found on First Deployment

### ISSUE THREAD

**Issue by rezytijo** [OneUptime/oneuptime#1425]
**Describe the bug**
i run this project on ARM Server using Docker Compose, after that i got **Error: Status Page ID not found** 

**To Reproduce**
1. Go to 'config.env'
2. Change on HOST=0.0.0.0 IP & HTTP_PROTOCOL=http
3. Run using ./install.sh or command on github
4. See error in the browser

**Expected behavior**
i want to try this project on my homelab server

**Screenshots**
![image](https://github.com/OneUptime/oneuptime/assets/28909046/43890cbb-9cb1-4d39-8832-c4498a62e158)

**Desktop (please complete the following information):**
 - Windows 11
 - Chrome
 - 124.0.6367.209 (Official Build) (64-bit) (cohort: Control) 

**Deployment Type**
Self Hosted on OCI Ampere Server (ARM Processor) Ubuntu 22.04, Docker Engine 26.0

**Comment by simlarsen** [comment]
Please access your site by your host IP. In this case 0.0.0.0

**Comment by rezytijo** [comment]
> Please access your site by your host IP. In this case 0.0.0.0

OK, we alredy now with that, but still facing same issue.
Now we have new issue 
![image](https://github.com/OneUptime/oneuptime/assets/28909046/7a27143d-9429-4c38-b3e1-9cb9cf71031c)

**Comment by moda20** [comment]
I also have this issue, can't seem to fix it. I do access my site using the IP and port i setup in the .env

**Comment by rezytijo** [comment]
Hello everyone, now i really now how to fix this issue.

On **config.env**  we have to use the original address that we use to access the login page, for example if VPS using IP 192.168.10.20 then enter HOST=192.168.10.20

If using a domain, what we put there is a domain
HOST=oneuptime.local

If using a Public IP, what we put there is a Public IP

Then for ports we can only use port 443 or 80, don't use other ports
Remember if using domain, we need to install reverse proxy to provide SSL for HTTPS, personally i use installed reverse proxy on another VPS or just using Cloudflare with ZeroTrust Tunnel Agent.

On Reverse Proxy we should use only http://<oneuptime> but on the config.env we use https on **HTTP_PROTOCOL**
