### ISSUE TITLE
Fix: GitHub actions jobs dont run on PR's from forked repo. 

### ISSUE THREAD

**Issue by simlarsen** [OneUptime/oneuptime#143]
This PR is from the main repo: https://github.com/OneUptime/oneuptime/pull/125#partial-pull-merging

This PR is from the forked repo: https://github.com/OneUptime/oneuptime/pull/136

If you notice the list of jobs that runs, the PR from the main repo has 33 jobs and PR from the forked repo just have 3. We need to make sure PR from the forked repo can run all the jobs as PR from the main repo. 

Please investigate and send a Pr for the fix.

**Comment by Reneuwumuhire** [comment]
The issue was fixed in the previous PR. needs to be closed
