### ISSUE TITLE
Bug: changing the timeout for workflow execution (5s)

### ISSUE THREAD

**Issue by yiren-liu** [OneUptime/oneuptime#1434]
**Describe the bug**
I attempted to build a custom workflow to perform API testing for an external server's endpoint (takes more than 5s), but facing a hard limit timeout of 5s. 
Is there a way to modify the workflow execution timeout in a self-hosted instance?

```
May 21 2024, 18:54 GMT: Executing Component: manual-1
May 21 2024, 18:54 GMT: Component Args:
May 21 2024, 18:54 GMT: {}
May 21 2024, 18:54 GMT: Component Logs: manual-1
May 21 2024, 18:54 GMT: Completed Execution Component: manual-1
May 21 2024, 18:54 GMT: Data Returned
May 21 2024, 18:54 GMT: {}
May 21 2024, 18:54 GMT: Executing Port: Execute
May 21 2024, 18:54 GMT: Executing Component: AI-Server
May 21 2024, 18:54 GMT: Component Args:
May 21 2024, 18:54 GMT: {[RETURNED_RESPONSE_HERE...]}
May 21 2024, 18:54 GMT: Component Logs: AI-Server
May 21 2024, 18:54 GMT: Completed Execution Component: AI-Server
May 21 2024, 18:54 GMT: Data Returned
May 21 2024, 18:54 GMT: {[RETURNED_RESPONSE_HERE...]}
May 21 2024, 18:54 GMT: Executing Port: Success
May 21 2024, 18:54 GMT: Workflow execution time was more than 5000ms and workflow timed-out.
May 21 2024, 18:54 GMT: Workflow Timed out.
Close
```

**To Reproduce**
1. Create a new workflow.
2. Build a new workflow to perform API testing and send alert to slack.
3. Manually trigger and wait.

**Expected behavior**
Maybe a setting for the workflow or the project to override the default timeout?

**Deployment Type**
Self hosted (7.0.2033)

**Comment by simlarsen** [comment]
Added `script.workflowScriptTimeoutInMs` in Helm Values 

`WORKFLOW_SCRIPT_TIMEOUT_IN_MS` if you're using Dodkcer Compose
