### ISSUE TITLE
Enhancement: GitHub Releases

### ISSUE THREAD

**Issue by TomKeur** [OneUptime/oneuptime#1437]
**Is your feature request related to a problem? Please describe.**
I'm following the releases of this project, I'm getting A LOT of e-mail for example:
<my local time> - <release name>
- 15:23 - Release 7.0.2354
- 14:25 - Release 7.0.2349
- 14:10 - Release 7.0.2346

This is going on all day long.

**Describe the solution you'd like**
Maybe only release after a whole day? With an automatic action?

**Comment by simlarsen** [comment]
Thank you for letting us know! We will make sure we work on this. Ideally 1 release a day.
