### ISSUE TITLE
Bug: Issue with Applying SSL Certificate to Self-hosted Docker Application

### ISSUE THREAD

**Issue by manojsomase** [OneUptime/oneuptime#1462]
Description:
I'm encountering difficulties applying an SSL certificate to self-hosted Docker application. Despite following standard procedures for SSL certificate installation, I'm unable to secure the application with HTTPS.

Steps Taken:

Generated SSL certificate using LetsEncrypt.
Attempted to apply the SSL certificate to the Docker container.
Checked NGINX configuration and Docker container ports for conflicts.
Verified SSL certificate validity and correctness.
Issue:
Despite completing the above steps, HTTPS is not functioning, and the application remains insecure.

Additional Information:

Docker container is self-hosted and running on Ubuntu.
NGINX is used as the web server within the Docker container.
The SSL certificate is valid and has been successfully applied to other non-Docker applications.
Request:
Seeking assistance in troubleshooting and resolving the issue to successfully apply the SSL certificate to the self-hosted Docker application, enabling secure HTTPS connections.

Any guidance or suggestions would be greatly appreciated. Thank you.

**Comment by simlarsen** [comment]
TLS/SSL are not supported by OneUptime and you have to have a reverse proxy for it. Please read https://oneuptime.com/docs/installation/docker-compose for more info.
