### ISSUE TITLE
Bug: Profile Images broken

### ISSUE THREAD

**Issue by sevensolutions** [OneUptime/oneuptime#1478]
**Describe the bug**
It looks like the Profile Images are broken because they generate a wrong URL.
Closely inspecting the \<img\> tag shows, that the URL is missing a second slash after https:.
```
<img alt="User Profile" src="https:/oneuptime.mydomain.io/file/image/825384cf-cc8e-45d5-9042-f1347ba4be67" class="h-8 w-8 rounded-full">
```

**To Reproduce**
1. Upload a profile image
2. The image is not shown in the top right corner

**Expected behavior**
The image should be shown in the top right corner

**Screenshots**
<img width="534" alt="image" src="https://github.com/OneUptime/oneuptime/assets/84123899/015b489a-5b92-4cb8-ba04-7f8f629951b4">

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Tested in Chrome and Safari

**Deployment Type**
docker-compose

**Comment by AndersonOuverney** [comment]
here I have the same behavior.

**Comment by simlarsen** [comment]
Fixed here: https://github.com/OneUptime/oneuptime/pull/1633/commits/6fd43622a321cf01610b501411cab74979e5df3c

**Comment by simlarsen** [comment]
This will be released today.
