### ISSUE TITLE
Bug: Cannot create monitors 

### ISSUE THREAD

**Issue by andreaswendlandt** [OneUptime/oneuptime#1481]
**Describe the bug**
When trying to create a new monitor or duplicate an existing monitor i get a "Server Error" - see the attached Screenshots

**To Reproduce**
1. Go to the tab "Monitors"
2. Click the button "+ Create Monitor"
3. Fill in all values you want the monitor to have
4. Click the button Next
5. Fill in all values for the Criteria you want the monitor to have
6. Click the button Next
7. Select the Monitoring Interval you want the monitor to have
8. Click the button "Create Monitor"

**Expected behavior**
A new created Monitor

**Screenshots**
See the attached Screenshots

**Desktop (please complete the following information):**
 - Browsers: tested with chrome and firefox

**Deployment Type**
self hosted docker images 
last updated yesterday(12/06/2024) 
current dashboard version: 7.0.2525 

![Bildschirmfoto vom 2024-06-13 13-04-56](https://github.com/OneUptime/oneuptime/assets/3864371/a29e1179-6525-476c-bfbe-f2e5c49fd117)
![Bildschirmfoto vom 2024-06-13 10-22-04](https://github.com/OneUptime/oneuptime/assets/3864371/fb76dbdf-3526-44df-89fc-2c4ce881d353)

**Comment by simlarsen** [comment]
Can you please attach the logs from the `app` container.

**Comment by andreaswendlandt** [comment]
[oneuptime-app-1.log](https://github.com/user-attachments/files/15820526/oneuptime-app-1.log)

**Comment by simlarsen** [comment]
Since this is self-hosted and you dont have a support contract with us, there's nothing we can do unfortunately. 

Closing this issue.

**Comment by migaspar** [comment]
@andreaswendlandt 
After updating from 7.0.2380 to 7.0.2721, I experienced the same issue.
```SQL
ALTER TABLE "Monitor" ADD COLUMN "incomingMonitorRequest" jsonb;
ALTER TABLE "Monitor" ADD COLUMN "serverMonitorResponse" jsonb;
```
did the trick for me.
