### ISSUE TITLE
Bug: href to incident from monitor page incorrect

### ISSUE THREAD

**Issue by rowan-vr** [OneUptime/oneuptime#1486]
**Describe the bug**
When clicking the 'View Incident' button on the monitor page you are being redirected to the wrong url.

**To Reproduce**
1. Log in to the dashboard
2. Go to a monitor with incident(s).
3. Click on view Incident.
4. Observe

**Expected behavior**
Be redirected to https://oneuptime.domain/dashboard/[PROJECT]/incidents/[INICDENT ID]

**Actual behavior**
Being redirected to https://oneuptime.domain/dashboard/[PROJECT]/monitors/[MONITOR]/incidents/[INCIDENT ID] which results in a not found page

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: arch linux
 - Browser: google chrome
 - Version: 124.0.6367.60-1

**Smartphone (please complete the following information):**
N/A

**Deployment Type**
self hosted

**Additional context**
N/A

**Comment by simlarsen** [comment]
Thank you for reporting. This is fixed!
