### ISSUE TITLE
Bug: https does not work in self hosted oneuptime instance with docker compose

### ISSUE THREAD

**Issue by kumaranvpl** [OneUptime/oneuptime#1493]
**Describe the bug**
I have followed the steps in this link https://oneuptime.com/docs/installation/docker-compose to set up a self-hosted oneuptime instance. I got a letsencrypt certificate for my subdomain `monitoring.mydomain.com`. 

My edited `config.env` looks like
```txt
HOST=monitoring.mydomain.com
HTTP_PROTOCOL=https
STATUS_PAGE_CNAME_RECORD=monitoring.mydomain.com
```

When I start the docker containers with the `docker compose` command and navigate to the URL `https://monitoring.mydomain.com`, the dashboard/page does not load. 

Looking through the logs of nginx container shows the following log entries
```txt
2024/06/18 05:00:00 [error] 31#31: *1 cannot load certificate "/etc/nginx/certs/StatusPageCerts/monitoring.mydomain.com.crt": BIO_new_file() failed (SSL: error:80000002:system library::No such file or directory:calling fopen(/etc/nginx/certs/StatusPageCerts/monitoring.mydomain.com.crt, r) error:10000080:BIO routines::no such file) while SSL handshaking, client: 49.204.143.29, server: 0.0.0.0:7850
2024/06/18 05:00:00 [error] 30#30: *2 cannot load certificate "/etc/nginx/certs/StatusPageCerts/monitoring.mydomain.com.crt": BIO_new_file() failed (SSL: error:80000002:system library::No such file or directory:calling fopen(/etc/nginx/certs/StatusPageCerts/monitoring.mydomain.com.crt, r) error:10000080:BIO routines::no such file) while SSL handshaking, client: 49.204.143.29, server: 0.0.0.0:7850
```

But if I update the config and set `HTTP_PROTOCOL=http`, then the oneuptime dashboard loads properly in `http://monitoring.mydomain.com`.

Am I supposed to run any scripts before starting `docker compose`?

I looked at `Scripts` dir and found this https://github.com/OneUptime/oneuptime/blob/master/Scripts/Install/LetsEncrypt/certs-issue.sh script. Running the `certs-issue.sh` does not change the https behavior. 

**Expected behavior**
Dashboard should load in https

**Deployment Type**
self hosted; deployed using docker compose.

**Comment by simlarsen** [comment]
We have added a section on setting uo TLS/SSL. Maybe that could help. https://github.com/OneUptime/oneuptime/blob/master/App/FeatureSet/Docs/Content/installation/docker-compose.md
