### ISSUE TITLE
Docker Probe Container: Ping Monitoring is disabled

### ISSUE THREAD

**Issue by meifi** [OneUptime/oneuptime#1586]
Hi, 

we've installed oneuptime on Ubuntu 24.04 LTS with docker. But we cant use monitor type ping. on the admindashboard it says offline. dockerlogs for default probe and a manually added probe shows in log the following:

```
docker container logs oneuptime-probe

> @oneuptime/probe@1.0.0 start
> node --require ts-node/register Index.ts

App Version: 7.0.2774
(node:19) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
Ping monitoring is disabled on this machine. Fallback to port monitoring
Ping monitoring is disabled
```

**Comment by simlarsen** [comment]
It should say online on admin dashboard. ICMP checks are usually disabled on cloud providers, so ping checks wont work there if you're installing a porbe on the cloud provider.

**Comment by simlarsen** [comment]
Please feel free to re-open this issue if you have any questions.

**Comment by meifi** [comment]
thank you for your response. 
It is there any option to enable ICMP checks on Cloud Providers ?

**Comment by simlarsen** [comment]
Unfortunately no way to enable that. They do it to prevent ICMP attacks.

**Comment by meifi** [comment]
But when i use the software in our own system environment it is a necessary check to make this usable. we've installed probes via docker on our own root servers at public hosters and on our own datacenter. on booth we've the problem, that pingmonitoring ist disabled. 

how can the software find out that its a software on a public cloud provider?

**Comment by simlarsen** [comment]
We dont find the software is on cloud provider. When you run the probe, we try to ping major websites (google.com) for example and if that doesnt work, we disbale ping.

**Comment by meifi** [comment]
But when we run this software at our own datacenter, ping is also disabled. when we try so ping or access the websites from the dockerhost, which are listed in the sourcecode for the probe, so we've no problem. 

We've also startet a container and check directly. we can reach all domains. 
```docker run -ti mmoy/ubuntu-netutils bash```

**Comment by meifi** [comment]
We installed another status page yesterday for testing purposes. ping / icmp probes are possible here without any problems. Is it possible that this is an error in the check when starting the probe container?

**Comment by simlarsen** [comment]
Hmm.. Let me re-open this issue and look into it.

**Comment by simlarsen** [comment]
We found the issue. This is fixed and will be released by EOD today.

**Comment by meifi** [comment]
Perfect, many thanks. its working now :)
