### ISSUE TITLE
Bug : selfhosted, can't redirect the /api route to a specific port

### ISSUE THREAD

**Issue by moda20** [OneUptime/oneuptime#1594]
**Describe the bug**
i am hosting the oneUpTime locally using docker on my server local IP and a specific port 8080 and i can't get the dashboard to work. i am getting this error : 
![image](https://github.com/user-attachments/assets/d1f2bb56-3945-4309-b142-a37a73552909)

**To Reproduce**
1. setup the .env to use a static ip and a local port in the .env, 
2. run the docker compose command 

**Expected behavior**
i can access the dashboard 

**Screenshots**
![image](https://github.com/user-attachments/assets/d1f2bb56-3945-4309-b142-a37a73552909)

**Desktop (please complete the following information):**
 - OS: macOs 12
 - Browser: chrome

**Deployment Type**
self hosted using docker

**Comment by simlarsen** [comment]
You need to specify the port as well in the HOST env var
