### ISSUE TITLE
Error email notifications: "Global configuration for SMTP not found" 

### ISSUE THREAD

**Issue by luisxkimo** [OneUptime/oneuptime#1600]
**Describe the bug**
"Global configuration for SMTP not found" error when system tries to notify any user or team member about changes in the project.

**To Reproduce**
1. Generate any kind of action that notify to users, for example, with an owner of an incident configured, make a change of the status line, to notify to the owners of the incident

**Expected behavior**
An email should be received by all owners about the changes of the status of the incident.

**Deployment Type**
Self Hosted with HELM Chart. 

**Additional context**
Checked that "Zero" config is in database.

And button of "Send Test email" notification in project settings its working and test email is received.

**Screenshots**

![image](https://github.com/user-attachments/assets/e550d98b-e631-4557-a6e6-2725cc4434aa)

![image](https://github.com/user-attachments/assets/32cb6a4d-938d-4ff0-816f-7c588a715aa6)

![image](https://github.com/user-attachments/assets/623d79f8-e049-4073-9b34-6e9e800f58bd)

![image](https://github.com/user-attachments/assets/31f7e10d-3d6a-4c7a-81d5-83542e895377)

![image](https://github.com/user-attachments/assets/3ce70218-ee01-4eda-ab7f-88210456648f)

**Comment by luisxkimo** [comment]
Hi @simlarsen 

Sure, here is:

![image](https://github.com/user-attachments/assets/07b7964c-a2cf-44d5-b13b-e91d33b48ee2)

**Comment by simlarsen** [comment]
This is because you dont have an SMTP username. Can you please add that and retest?

**Comment by luisxkimo** [comment]
In my case, username and password its not needed for our internal proxy email server.

Anyway, I tried adding a username without password, and I have same behavior. Here is the error in the log of the container "app":

![image](https://github.com/user-attachments/assets/248696e3-8993-47f0-b85c-d724d2b135e9)

**Comment by luisxkimo** [comment]
To clarify: we are using an internal "open relay" email server without auth, so we "cannot" configure and user and password because we haven't any available to use it as SMTP configuration.

**Comment by simlarsen** [comment]
We found the issue. This is fixed and will be released by EOD today.

**Comment by luisxkimo** [comment]
Confirmed in our side that now its working. Thanks for the quick fix
