### ISSUE TITLE
Status Page Resources Throws Error when there is two Monitor Group added to Status Page Resource

### ISSUE THREAD

**Issue by Johncs2d** [OneUptime/oneuptime#1601]
**Describe the bug**
The Status Page won't load when you add more than one monitor group in group page resource in the status page

**To Reproduce**
1. Go to Status Page, then in the resource tab of create a status page resources. Add two group monitor in that status page resources.
2. Open the status page preview
3. See the error ```TypeError: Cannot read properties of undefined (reading 'priority')```

**Expected behavior**
The Status page should load normally without error

**Screen
![Screenshot 2024-07-24 at 9 16 11 PM](https://github.com/user-attachments/assets/f1b9d340-9c18-4612-9895-d2e201c0d849)
shots**
![Screenshot 2024-07-24 at 9 19 18 PM](https://github.com/user-attachments/assets/0726ea20-86e5-44ec-a187-dc98b9199589)

**Desktop (please complete the following information):**
 - OS: MAC
 - Browser: Chrome
 - Version: Latest

**Deployment Type**
self hosted: Helm oneuptime 7.0.2828

**Comment by simlarsen** [comment]
Thank you for letting me know! This is now fixed. Will be releaed by EOD today.
