### ISSUE TITLE
Enable create incidents by webform without "Resources Affected"

### ISSUE THREAD

**Issue by luisxkimo** [OneUptime/oneuptime#1608]
**Is your feature request related to a problem? Please describe.**
Can't create incidents without Monitor associated using webform

**Describe the solution you'd like**
Remove required field notifications for "monitor affected" in the incident creation using webform, because by API its possible create in this way.

**Additional context**

![image](https://github.com/user-attachments/assets/862e6975-bd4d-4986-9bd2-5af2ac1b6e94)

![image](https://github.com/user-attachments/assets/64b5e67c-024b-45b7-8442-1ae19ad6e040)

**Comment by simlarsen** [comment]
This is fixed and will be released by EOD today.

**Comment by luisxkimo** [comment]
Confirmed in our side that now its working as expected. Thanks so much for the quick implementation
