### ISSUE TITLE
Multiple Status Code on 1 Criteria

### ISSUE THREAD

**Issue by rezytijo** [OneUptime/oneuptime#1616]
i want to ask, are we can add Multiple Status code using dash or separated using coma?

![image](https://github.com/user-attachments/assets/05b84714-9b51-427d-b034-a15564622455)

**Comment by simlarsen** [comment]
No this is not possible.

**Comment by rezytijo** [comment]
Thankyou for your confirmation, i hope this will be implemented on future update
