### ISSUE TITLE
"IF / Else" does not support null on secondary input in workflow builder GUI

### ISSUE THREAD

**Issue by Kuldran** [OneUptime/oneuptime#1630]
**Describe the bug**
you cannot use an if/else block to do a null object check.

**To Reproduce**

- Create a find incident block (look for something that returns null?)
- Link it to a if option
- In an if statement set param 1 as object, and param 2 null cannot be specified for 'Equals to' and not

**Expected behavior**
Should be able to check for null.

**Screenshots**
![image](https://github.com/user-attachments/assets/d6fc8e7c-142a-4703-9f41-20682662935e)

**Desktop (please complete the following information):**
 - Browser chrome, chromium, firefox-sre
 - Version what ever is on debian sid.

**Deployment Type**
tested on self hosted

**Additional context**
see slack for info.

**Comment by rshunter05** [comment]
We would be very interested in this too

**Comment by simlarsen** [comment]
<img width="645" alt="image" src="https://github.com/user-attachments/assets/02f1ea44-08f1-4062-aec7-8b109774607d">


This should now work. Please let me know if this helps!
