### ISSUE TITLE
Use middle button mouse to open new tab any item in website

### ISSUE THREAD

**Issue by luisxkimo** [OneUptime/oneuptime#1634]
**Describe the solution you'd like**

Clicking using "middle" mouse button usually opens new links and sections in a new tab in the browser. This could be very usefull to open quickly some sections without change the context of the current section

For example, clicking on "Monitors" and "Incidents" using middle mouse button, open this sections in two new tabs, keeping my current view (for example "Home" open in my current tab.

Other useful cases is being in the list of incidents, clicking with middle button on some incidents names, open each incident in a new tab, to check something quickly without lose list view

**Comment by simlarsen** [comment]
This is fixed! will be released today.

**Comment by luisxkimo** [comment]
Confirmed that works for the upper menu items. Thanks for the quick implementation.
