### ISSUE TITLE
Increase functionality of If/Else component in workflows

### ISSUE THREAD

**Issue by luisxkimo** [OneUptime/oneuptime#1635]
**Is your feature request related to a problem? Please describe.**
This component its very limited to implement a bit more complex operations to compare, for example "contains/not contains" or add more than 2 input values and AND/OR operators between them.

**Describe the solution you'd like**
There are  some options that we could have here, one of them could be:

1. Let add input files as the user wants (maybe with a high limit to avoid performance issues)
2. Add functions like AND/OR between conditions
3. Add more operations like "contains", "no contains", "is empty",
4. NICE TO HAVE: have at least 2 levels of "nesting" in if/else conditions

**Comment by Kuldran** [comment]
That would be something I to would be interested in.
