### ISSUE TITLE
Monitor Summary - Hostname or IP Address

### ISSUE THREAD

**Issue by AndersonOuverney** [OneUptime/oneuptime#1638]
**Describe the bug**
When opening a monitor, there is a field called
Monitor Summary
There is a field called hostname or ip
The following information is displayed in this field
[object Object]

**To Reproduce**
1 - Go to a monitor page
2 - Look at the monitor summary field

**Expected behavior**
I believe the IP or hostname of what is being monitored should appear?

**Screenshots**
![image](https://github.com/user-attachments/assets/0c736c6f-4d29-4b07-a151-b0910fcfcd83)

**Comment by simlarsen** [comment]
This is fixed and will be released today: https://github.com/OneUptime/oneuptime/commit/a6cb80f64053999b06678f355b21c0d85faa1044
