### ISSUE TITLE
Does not allow domains like (.africa)

### ISSUE THREAD

**Issue by damey2011** [OneUptime/oneuptime#1642]
**Describe the bug**

**To Reproduce**
1. Go to 'More'
2. Click on 'Domains'
3. Add new domain "company.africa"

**Expected behavior**
Let's you add the domain

**Deployment Type**
Self hosted

**Comment by simlarsen** [comment]
Done! https://github.com/OneUptime/oneuptime/pull/1643 

Will be released today.
