### ISSUE TITLE
Allow anonymous configuration in Sent Email componente in Workflows

### ISSUE THREAD

**Issue by luisxkimo** [OneUptime/oneuptime#1661]
**Is your feature request related to a problem? Please describe.**
I would like to use our internal relay email server to send emails in workflows. 

The problem is this kind of email servers (relay proxy) doesn't have any security configurations, in terms of user+password

**Describe the solution you'd like**
The proposal is remove the restriction to add user and password in the component "Send Email" for workflows (or allow user and password empty fields)

![image](https://github.com/user-attachments/assets/c9e5d87f-0706-479c-9c6c-4fb9ed1f57dc)

**Comment by simlarsen** [comment]
This is implemented and fixed and will be released today.
