### ISSUE TITLE
Error on button "View Timeline" from "On-Call Policy Logs"

### ISSUE THREAD

**Issue by luisxkimo** [OneUptime/oneuptime#1662]
**Describe the bug**
The button "View Timeline" in "On-Call Policy Logs" returns blank website, with error on the browser console

**To Reproduce**
1. Create an On-Call policy and "force" an execution
2. Go to details of the On-Call policy, section "Execution Logs"
3. Click on "View Timeline"

**Expected behavior**
Show the timeline execution or something similar

**Screenshots**

![oncall_timeline_error](https://github.com/user-attachments/assets/bba77c4d-e17b-4a85-ba05-f2f32202e535)

**Error on browser console**

![oncall_timeline_error_browser_log](https://github.com/user-attachments/assets/30dea2ad-08ff-4d77-913d-c7814edf5981)

**Desktop (please complete the following information):**
 - Browser : Edge
 - Version 7.0.2994

**Deployment Type**
Helm chart

**Additional context**

**Comment by simlarsen** [comment]
Thank you for reporting. This is fixed and will be released today.
