### ISSUE TITLE
Add option of "existingSecret" for oneuptimeSecret and encryptionSecret

### ISSUE THREAD

**Issue by luisxkimo** [OneUptime/oneuptime#1675]
**Is your feature request related to a problem? Please describe.**

We can't use "external" secrets to add custom values for _oneuptimeSecret_ and _encryptionSecret_. This makes _insecure_ this secret when we want to upload the helm values file to a repository.

**Describe the solution you'd like**
Like in the configuration of _externalPostgres_, add to the configuration of the Helm chart to enable use custom existing secret.

**Describe alternatives you've considered**
If I'm right, in _helpers.tpl should be something like this:

```
- name: ONEUPTIME_SECRET
  {{- if $.Values.oneuptimeSecret }}
  value: {{ $.Values.oneuptimeSecret }}
  {{- else }}
  
  {{- if $.Values.externalOneuptimeSecret.existingSecret.name }}
  valueFrom:
    secretKeyRef:
        name: {{ printf "%s" $.Values.externalOneuptimeSecret.existingSecret.name }}
        key: {{ $.Values.externalOneuptimeSecret.existingSecret.passwordKey }}
  {{- else }}
  valueFrom:
    secretKeyRef:
      name: {{ printf "%s-%s" $.Release.Name "secrets"  }}
      key: oneuptime-secret
  {{- end }}
  {{- end }}
```

Same for ENCRYPTION_SECRET

**Comment by simlarsen** [comment]
This is merged in already. Closing this.
