### ISSUE TITLE
Stop execution escalation rules when incident is resolved

### ISSUE THREAD

**Issue by luisxkimo** [OneUptime/oneuptime#1690]
**Is your feature request related to a problem? Please describe.**
The escalation rules configured in a On-Call policy are executed event when the incident related with the policy is resolved.

**Describe the solution you'd like**
With a configuration of escalation rules based on time, I would like have a configuration to "stop" the execution of the escalation rules when the incident is resolved.

**Describe alternatives you've considered**
Nice to have could be have other option to stop execution os escalation rules when the incident is "ACK" by someone (individual or someone in a group)

**Comment by simlarsen** [comment]
@luisxkimo do you want to give it a shot and contribute?

**Comment by simlarsen** [comment]
This is done! https://github.com/OneUptime/oneuptime/pull/1693 I beat you to it ;)

**Comment by luisxkimo** [comment]
Awesome! I didn't think you could have it so soon! 

I will update my instance and check right now.

Great job and many many thanks :D 👏 👏
