### ISSUE TITLE
Create issues to test Common/Utils

### ISSUE THREAD

**Issue by nawazdhandala** [OneUptime/oneuptime#17]
You can break this issue down into multiple issues.

We have lots of Common/Utils. Ideally, there should be 1 issue for each of those types in Common/Utils. Create 1 issue for each of those utils and close this issue.

Labels for those issues: good first code

**Comment by munezerobagira** [comment]
created issues #37 #34 #33

**Comment by nawazdhandala** [comment]
Great since we have those issues up. Closing this issue.
