### ISSUE TITLE
Overkill on delete cascade + Project Custom SMTP

### ISSUE THREAD

**Issue by hart1dechu** [OneUptime/oneuptime#1706]
**Describe the bug**
Two things:
- I feel like some on delete cascade constraint in the database are way too overkill. One example that occur to me, and was really confused about it, was the Status Page, when having a ProjectSMTP mail subscriber, and bu deleting that Project SMTP, instead of not having a mail subscriber in the status page, you just dont have a Status Page anymore
- Project SMTP doesnt seem to override Global SMTP

**To Reproduce**
- Setup yourself a Project Custom SMTP and a Global Custom SMTP that are both different. Invite someone to your team, and look which SMTP is used
- Create a Status Page, Go to `View this status Page > Subscriber Settings > Custom SMTP`. Set your previously made Custom SMTP. Delete hat previous made SMTP

**Expected behavior**
- For the invite team member, it should use the project SMTP instead of Global as it should override the Global
- For the Status Page, deleting the Custom Project SMTP linked to the Subscriber Settings should just remove the SMTP from the status page. Not the entire page.

**Deployment Type**
Self Hosted OneUptime version 7.0.2666

**Comment by simlarsen** [comment]
This is fixed! I've also removed the cascade from other places as well. Please upgrade your cluster.
