### ISSUE TITLE
Status Page Throws Error when there isa Monitor Group added to Status Page Resource

### ISSUE THREAD

**Issue by Johncs2d** [OneUptime/oneuptime#1709]
**Describe the bug**
The Status Page won't load when you add more than one monitor group in group page resource in the status page

**To Reproduce**
1. Go to Status Page, then in the resource tab of create a status page resources. Add a group monitor in that status page resources.
2. Open the status page preview
3. See the error ```TypeError: Cannot read properties of undefined (reading 'id')```

**Expected behavior**
The Status page should load normally without error

**Screenshots**

![image](https://github.com/user-attachments/assets/ab68d189-1876-488c-957f-51add0a6c2a1)

**Desktop (please complete the following information):**
 - OS: MAC
 - Browser: Chrome
 - Version: Latest

**Deployment Type**
self hosted: Helm oneuptime 7.0.3086

Kind of related but slightly different to this issue https://github.com/OneUptime/oneuptime/issues/1601

**Comment by simlarsen** [comment]
This is now fixed. Thank you for reporting!
