### ISSUE TITLE
Your project is not active because some invoices are unpaid. - Payment not working

### ISSUE THREAD

**Issue by zfpgroup** [OneUptime/oneuptime#1712]
**Describe the bug**
Info on web: Your project is not active because some invoices are unpaid.

Trying to pay:
 
Something is not quite right...
Invoice ID not found

![Snímek obrazovky 2024-09-23 v 16 05 41](https://github.com/user-attachments/assets/67463661-d637-419b-9085-eed15c9e11b9)

**Comment by simlarsen** [comment]
Looking into this.

**Comment by simlarsen** [comment]
Deploying in an hour.
