### ISSUE TITLE
Not able to use oneuptime in offline environment

### ISSUE THREAD

**Issue by quadeare** [OneUptime/oneuptime#1724]
**Describe the bug**
I successfully deployed Oneuptime in an offline environment. Unfortunately, the UI is not working well due to missing online front libraries.

**To Reproduce**
1. Deploy Oneuptime in offline environment
2. Open web-browser and reach public URL

**Expected behavior**
We should be able to use Oneuptime in any environment.

**Screenshots**
![Capture](https://github.com/user-attachments/assets/a3b080c3-3da4-401e-b4a6-933c9070c9e5)

**Desktop (please complete the following information):**
 - OS : Ubuntu 24.04
 - Browser : Firefox
 - Version : 130.x

**Deployment Type**
Self-hosted deployment

**Comment by simlarsen** [comment]
This should be fairly easy issue. Can you please create a Pr for this?
