### ISSUE TITLE
Invalid cluster key provided in ingestor container

### ISSUE THREAD

**Issue by RegisHubelia** [OneUptime/oneuptime#1752]
**Describe the bug**
Since the last release, I get Invalid cluster key provided in the ingestor and probes cannot connect.  I did the usual to update (npm run update) - and all went well, but I still have this error...

**Comment by simlarsen** [comment]
Looking into this. Should be fixed by end of tomorrow.

**Comment by RegisHubelia** [comment]
Thank you for the quick reply and quick resolution.  Looking at your commits today seems like a busy day around probes!

**Comment by simlarsen** [comment]
Apologies for the late reply. This is now fixed.

**Comment by RegisHubelia** [comment]
Thank you.  That issue is fixed, but there is a new issue.  I'll create a separate issue.
