### ISSUE TITLE
css loading problem 

### ISSUE THREAD

**Issue by Sundhar22** [OneUptime/oneuptime#1764]
Describe the bug
CSS resources are not loading properly on oneuptime.com, causing styling issues on the website.

To Reproduce

Go to 'https://oneuptime.com/'
Observe the page loading
CSS styles are not applied correctly, resulting in unstyled or improperly styled elements
Expected behavior
All CSS styles should load properly and be applied to the page elements, resulting in a properly styled and formatted website.

**Comment by simlarsen** [comment]
Can you please attach screenshot.

**Comment by Sundhar22** [comment]
I think this is not an original style

**Comment by simlarsen** [comment]
Seems to work for me. Are you sure this is not an issue on your end?

**Comment by Sundhar22** [comment]
yes I checked  in three browsers at the same time here is the reference image  
![Screenshot 2024-12-09 213440](https://github.com/user-attachments/assets/aed71f6d-b303-4987-ab80-c140b5e5d2e2)

**Comment by Sundhar22** [comment]
![Screenshot 2024-12-09 213659](https://github.com/user-attachments/assets/47000b31-25a6-4939-92c8-4d3cd2ba69e8)
in console

**Comment by Sundhar22** [comment]
please check hosted site - https://oneuptime.com/

**Comment by simlarsen** [comment]
Looks like tailwind is not loading on your machine. Please try in another browser. This is not OneUptime issue.

**Comment by Sundhar22** [comment]
Yes I don't know why in my wifi I can't see CSS loading but I can see the website working smoothly on my mobile network, sorry my mistake.
