### ISSUE TITLE
Double Opt-In (DOI) for new subscribers

### ISSUE THREAD

**Issue by ThoSt81** [OneUptime/oneuptime#1766]
**Is your feature request related to a problem? Please describe.**
We've just realized that this wasn't an option yet (or we could not find the setting) and our customers have now highlighted this as problematic flaw (as DOI is also recommended if not required under GDPR).

**Describe the solution you'd like**
When a user subscribes (or is subscribed) via email, an email confirmation (opt-in) should be send to the entered email address to confirm the subscription. Without this confirmation, the email subscription should remain inactive and ultimately be removed/canceled.

**Comment by simlarsen** [comment]
This is now implemented!
