### ISSUE TITLE
Make helm chart avaiilable for open-source users 

### ISSUE THREAD

**Issue by jgreat** [OneUptime/oneuptime#343]
**Describe the bug**

1. Chart repo install step is returning 404:

```
helm repo add oneuptime https://oneuptime.com/chart

Error: looks like "https://oneuptime.com/chart" is not a valid chart repository or cannot be reached: failed to fetch https://oneuptime.com/chart/index.yaml : 404 Not Found
```

2. MongoDB and Redis configuration sections are reversed. 

Looking forward to trying it out.

**Comment by altokarev** [comment]
+1

It seems microservices deployment via Helm should be more comfortable in use rather than Docker. 

Looking forward to trying out the chart.

**Comment by kashalls** [comment]
@jgreat @antokarev

Looks like a helm-chart was made available: https://github.com/oneuptime/helm-chart

**Comment by simlarsen** [comment]
Closing this issue since Helm Chart is now released.
