### ISSUE TITLE
Can't change monitor type

### ISSUE THREAD

**Issue by GewoonJaap** [OneUptime/oneuptime#350]
**Describe the bug**
When trying to create a new monitor I cannot select the monitor type
![image](https://user-images.githubusercontent.com/33700526/215506537-86c5fd59-86b9-41e7-be1d-b4efa7a998b5.png)

**To Reproduce**
1. Click create a new monitor
2. Observe the lacking type selector

**Expected behavior**
Should show a type selector

**Screenshots**
![image](https://user-images.githubusercontent.com/33700526/215506747-4cd0ed14-75a2-4d83-b5f4-a69b4718f20c.png)

**Desktop (please complete the following information):**
 - OS: Windows 11 Pro, Using Microsoft Edge

**Additional context**

**Comment by GewoonJaap** [comment]
I also tried Firefox, but still couldn't see the options. Also when editing the monitor there is no way to change the type

**Comment by simlarsen** [comment]
Fixed!
