### ISSUE TITLE
Disabling Email Verification option

### ISSUE THREAD

**Issue by jhuynh08** [OneUptime/oneuptime#356]
**Is your feature request related to a problem? Please describe.**
When installed locally in a cloud environment like AWS, outgoing emails cannot be set over port 25 since AWS blocks this port.

**Describe the solution you'd like**
Option to disabled email verification or ability to just create local user accounts

**Comment by Chillrend** [comment]
**Workaround**

Not the solution, but, in the meantime, you can just see logs from the `oneuptime-mail-1` container with:
```
docker logs oneuptime-mail-1
````
and then see the verification link for the user in the log, for example:
```
{
  message: 'Request ID: 7a4d2aa0-ac1d-11ed-8a9a-99b27d1a1a27 -- POD NAME: NONE -- METHOD: POST -- URL: /email/send\n' +
    ' Request ID: 7a4d2aa0-ac1d-11ed-8a9a-99b27d1a1a27 -- Request Body: {\n' +
    '  "toEmail": "test_user@example.xyz",\n' +
    '  "subject": "Welcome to OneUptime. Please verify your email.",\n' +
    '  "templateType": "SignupWelcomeEmail.hbs",\n' +
    '  "vars": {\n' +
    '    "name": "Test User",\n' +
    '    "tokenVerifyUrl": "https://oneuptime.xyz/accounts/verify-email/7a400b40-ac1d-11ed-b775-8f755056301b",\n' +
    '    "homeUrl": "https://oneuptime.xyz/"\n' +
    '  },\n' +
    '  "clusterKey": "82f98a4bce16a09978c7cacf"\n' +
    '}',
  level: 'info',
  timestamp: '2023-02-14T04:10:12.427Z'
}
```

**Comment by kashalls** [comment]
I believe this was fixed in https://github.com/OneUptime/oneuptime/releases/tag/7.0.645.

**Comment by simlarsen** [comment]
Closing this issue.
