### ISSUE TITLE
What are the server requirements?

### ISSUE THREAD

**Issue by Quin452** [OneUptime/oneuptime#358]
**Describe the bug**
I cannot find any mention as to what the server requirements are, outside of "Deploy a single-server instance in one line on Debian / Ubuntu with Docker (recommended 8GB memory, we only support Debian / Ubuntu as of today)."

But I run "preinstall", and get a LOT of errors (missing packages, node, etc.), which is odd, since I expect the pre-install to install all of these.

**Comment by simlarsen** [comment]
Can I please get the log?

**Comment by simlarsen** [comment]
Feel free to re-open this issue with you have logs.
