### ISSUE TITLE
Scheduled Maintenance - Manual status changes

### ISSUE THREAD

**Issue by VA2XJM** [OneUptime/oneuptime#368]
**Describe the bug**
While making tests on the cloud version, I noticed what could be considered an improvement needed "bug".

When working with SM(Scheduled Maintenance), 3 emails are sent: 1) When SM is created; 2) When SM starts; and 3) When SM ends.

If a SM is manually started using the dashboard in advance of schedule, emails 2 will be sent at scheduled time.

If a SM is manually completed using the dashboard in advance of schedule, emails 3 will never be received.

**To Reproduce**
1. Create a SM
2. Ahead of scheduled start time, change the state to ongoing.
3. Receive an email on scheduled start time.
4. Ahead of scheduled end time, change the state to completed.
5. No email will be received when end time is past.

**Expected behavior**
The function to change status to ongoing and completed should call email sending. The scheduler and the dashboard should call this function, so first status change (dashboard or scheduled) coming in will make status changes and emails be distributed.

**Additional context**
I have not reviewed any part of the code yet, so I may be wrong or it may already be fixed.

**Comment by simlarsen** [comment]
We have added new email architecture and this should no longer be an issue. Please let me know if you still face this.
