### ISSUE TITLE
Write tests for Common/Utils/Email

### ISSUE THREAD

**Issue by munezerobagira** [OneUptime/oneuptime#37]
There are no tests for `Common/Utils/Email/`, write  tests for it.

**Comment by munezerobagira** [comment]
Related issue
#57

**Comment by aphilas** [comment]
There is no such file `Common/Utils/Email.ts` or `Common/Utils/Email/index.ts` in [Common/Utils](https://github.com/OneUptime/oneuptime/tree/master/Common/Utils). Should this issue be closed (or updated)?

**Comment by simlarsen** [comment]
Can you please update it and write tests for that file.
