### ISSUE TITLE
Use the same custom domain for all status pages

### ISSUE THREAD

**Issue by sdouche** [OneUptime/oneuptime#377]
**Is your feature request related to a problem? Please describe.**
A custom domain is related to a status page and not set globally. so I need as many domains as status pages. Ex: 
So I have 3 products (a.mydomain.com, b.mydomain.com, c.mydomain.com) I need to set (status.a.mydomain.com, status.b.mydomain.com, status.c.mydomain.com).

**Describe the solution you'd like**
status.mydomain.com should be a better place for all status pages.

**Comment by simlarsen** [comment]
@sdouche which staus page should it go to if you navigate to status.mydomain.com?

**Comment by simlarsen** [comment]
Closng this becuase of no response from OP. Feel free to re-open this when you have a response.
