### ISSUE TITLE
boot up hangs with no install

### ISSUE THREAD

**Issue by robetus** [OneUptime/oneuptime#382]
**Describe the bug**
Upon install with no errors the booting of oneuptime just hangs, waited for about an hour and then aborted.

**To Reproduce**
1. Iinstall on Ubuntu 22.04 KVM server

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04
 - Browser: All
 - Version: 22.04

**Comment by simlarsen** [comment]
Can I have logs?

**Comment by robetus** [comment]
Looks like you just committed something to the repo entitled "add logs", can you tell me how I can export the logs to you from oneuptime? Or where are the install/boot logs located? I will do a fresh install and provide you the logs.

**Comment by simlarsen** [comment]
When you run `bash install.sh` can you please let me know what gets outputted to console?

**Comment by robetus** [comment]
I just installed it and: 🎉🎉🎉  Done! 🎉🎉🎉 

It worked normally this time but I get a warning. I'm sure it's something you know about and it's not an issue but I wanted to give it to you:

warning: you have specified the global option -maxdepth after the argument -type, but global options are not positional, i.e., -maxdepth affects tests specified before it as well as those specified after it.  Please specify global options before other arguments.

**Comment by robetus** [comment]
Just tried to install again and it hanged, before I could get it to install but now it's hanging again. Waited about 30 minutes.

**Comment by simlarsen** [comment]
Cant help without logs.
