### ISSUE TITLE
Helm repo doesn't exist

### ISSUE THREAD

**Issue by pab1it0** [OneUptime/oneuptime#394]
Helm repo doesn't exist

1. Go to https://github.com/OneUptime/oneuptime/tree/master/HelmChart/public/oneuptime#tldr
2. Exec 'helm repo add oneuptime https://oneuptime.com/chart'
3. `Error: looks like "https://oneuptime.com/chart" is not a valid chart repository or cannot be reached: failed to fetch https://oneuptime.com/chart/index.yaml : 404 Not Found`

**Comment by simlarsen** [comment]
We working on it. Will update this ticket when we launch.

**Comment by thebmw** [comment]
Is there a time estimate for when you plan to release this?

**Comment by Kashalls** [comment]
> Is there a time estimate for when you plan to release this?

When helm-charts are updated. I'm going to attempt to write them, never done it before.

**Comment by yonimoses** [comment]
Hi, 
Any update on that? Looking forward to trying it on k8s rather than VM.

**Comment by Kashalls** [comment]
> Hi, Any update on that? Looking forward to trying it on k8s rather than VM.

I haven't had much time to work on it. If you check my home cluster GitHub repo under kubernetes apps folders you can see the helm release way I am doing the containers

**Comment by simlarsen** [comment]
We'll launch this by end of this month (best case), first week of Oct (worst case). 

@Kashalls will look into yours and fork it.

**Comment by Kashalls** [comment]
> We'll launch this by end of this month (best case), first week of Oct (worst case). 
> 
> @Kashalls will look into yours and fork it. 

It's not something that can be forked easily. It's just a couple of manifests that use an app template developed by bjw-s

**Comment by simlarsen** [comment]
Closing this issue since Helm Chart is now released. 

https://artifacthub.io/packages/helm/oneuptime/oneuptime
