### ISSUE TITLE
How do I log in to my selfhosted instance?

### ISSUE THREAD

**Issue by luckman212** [OneUptime/oneuptime#405]
Sorry if this is a really dumb question, but... 🤷 

I set up a fresh Debian 11 host, installed all the prerequisites (curl, git, docker, snap, certbot etc) and pulled in the images without too much trouble. Even got the LetsEncrypt cert working with the `certs-issue.sh` script.

But... how do I log in? I can pull up the homepage but I don't have any login credentials, and don't see any default ones in the docs. Trying to register a new account results in a "server error".

**Comment by ninpartners** [comment]
good question

**Comment by simlarsen** [comment]
You need to register an account first and then you can log in. 

Can you please provide more logs from identity container?

**Comment by iOut1aw** [comment]
I have same issue here logs from indentity container:

```
~/oneuptime$ docker logs -f oneuptime-identity-1

identity@1.0.0 start
node --require ts-node/register Index.ts

Fri, 28 Apr 2023 06:28:57 GMT body-parser deprecated undefined extended: provide extended option at ../CommonServer/Utils/StartServer.ts:75:41
{
  message: 'identity server started on port: 3087',
  level: 'info',
  timestamp: '2023-04-28T06:29:17.117Z'
}
{
  message: 'Postgres Database Connected',
  level: 'info',
  timestamp: '2023-04-28T06:29:18.020Z'
}
{
  message: 'Redis connected on redis:6379',
  level: 'info',
  timestamp: '2023-04-28T06:29:18.037Z'
}
{
  message: 'Request ID: 082606e0-e58e-11ed-8d7d-474022cf55b7 -- POD NAME: NONE -- METHOD: GET -- URL: /identity/status\n' +
    ' Request ID: 082606e0-e58e-11ed-8d7d-474022cf55b7 -- Request Body: {}',
  level: 'info',
  timestamp: '2023-04-28T06:29:30.319Z'
}
```

**Comment by Peppershade** [comment]
I experience the same issue on the latest version of the release branch. Debian 11 installation, tried to remove everything and pull everything again, but still the same issue. Domain variable is set, app behind a (Traefik) reverseproxy. There are so many containers that I honestly don't know where to get the logs from.

**Comment by simlarsen** [comment]
Please re-open if you're still facing issues.
