### ISSUE TITLE
Incident/Maintenance Templates

### ISSUE THREAD

**Issue by BornTKill** [OneUptime/oneuptime#411]
**Is your feature request related to a problem? Please describe.**

It would more efficient to be able to create templates for incidents and maintenance.
Templates will allow to automatically add
- text
- Components affected
- Components status
- Etc …

When creating/updating incidents/maintenances the available template can be applied.

That is the way it works on statuspage.io 
Best regards.

**Comment by simlarsen** [comment]
On our roadmap. We're working on it.

**Comment by ThoSt81** [comment]
@BornTKill : Templates are now available, in case you have not noticed yet.

**Comment by simlarsen** [comment]
This is done a long time ago. Marking this issue as complete.
