### ISSUE TITLE
Status page navigation menu does not resize on mobile

### ISSUE THREAD

**Issue by arcticFox-git** [OneUptime/oneuptime#451]
**Describe the bug**
The navigation bar runs off the right side of the screen on mobile for status pages.

**To Reproduce**
1. Load a status page on mobile
2. Observe that the navigation menu runs off the right side of the screen

**Expected behavior**
The navigation menu would adjust to different screen sizes.

**Screenshots**

Screenshots were taken using responsive design in Firefox desktop browser for an iPhone 11, however I first observed the bug on mobile.

<img width="376" alt="Status_Page_Bug_Example1" src="https://github.com/OneUptime/oneuptime/assets/86988982/b6b1133c-408f-4775-882e-4e6ae7e490fc">
<img width="374" alt="Status_Page_Bug_Example2" src="https://github.com/OneUptime/oneuptime/assets/86988982/50227022-fd0d-4b9e-8101-6b49423e74d9">

**Smartphone (please complete the following information):**
 - Device: iPhone12
 - OS: iOS15
 - Browser: Safari

Additional Context:
Should be a very simple css fix

**Comment by simlarsen** [comment]
Fixed: https://github.com/OneUptime/oneuptime/commit/baec3734aae46aed947bee2c168cab7e686028ea. Deploy by EOD today.
