### ISSUE TITLE
Multiple Languages

### ISSUE THREAD

**Issue by torbenraab** [OneUptime/oneuptime#462]
**Is your feature request related to a problem? Please describe.**
I'm currently self hosting OneUptime and I'm very happy with it. As we currently only serve customers in Germany it would be nice to offer a translation for the basic UI elements.

**Describe the solution you'd like**
Use a library like i18n to create translations and let us contribute to the multiple language "packs". Also add the possibility to save a specific language to the profile and/or load based on browser.

**Describe alternatives you've considered**
Let everything in English only and deal with the customers. Preferably we could use different languages.

**Comment by teger** [comment]
yes, it's a good function

**Comment by kashalls** [comment]
This is a duplicate of #462. Although the requests are different, it is asking the same thing. I18N is possible, it needs to be done on the front end. [react-i18next](https://react.i18next.com) looks like a suitable fit for this. We need to discuss how we will get additional languages as well.

**Comment by torbenraab** [comment]
Closed because of Duplicate #372
