### ISSUE TITLE
Workflow Trigger Not Working - Monitor Criteria Generated Incident

### ISSUE THREAD

**Issue by bionemesis** [OneUptime/oneuptime#476]
It appears that workflows are not triggering when an incident is created due to a monitor criteria change. If an incident is created manually, workflows are triggered, but if an incident is created due to a criteria change (such as a website being offline or content changing), the workflow does not trigger and there is nothing in the workflow log.

**Comment by simlarsen** [comment]
Fixed here: https://github.com/OneUptime/oneuptime/commit/4277b8c1c43bca201f543a078e4bf1d7ca0ff88d
