### ISSUE TITLE
Inbound webhook passive/heartbeat monitoring

### ISSUE THREAD

**Issue by czb-ccoustier** [OneUptime/oneuptime#491]
**Is your feature request related to a problem? Please describe.**

We already have monitoring system internally that ping devices and send alerts when devices go down.  It is redundant to have to setup the monitor in two places.  With a passive monitor, OneUptime will be setup to take heartbeats from internal monitoring and any changes to devices only need to be updated in monitoring.  The heartbeat to OneUptime doesn't change.

**Describe the solution you'd like**

Have a configurable inbound/passive option for a component.  Either accept inbound email alerts to each component to change status or accept a webhook for each component to change status.  Another option is receiving a webhook at a configurable interval to maintain a online status, then if the heartbeat stops the component changes to offline.  Also, vice versa, the option to have a device show online by default, then if it begins receiving webhooks it changes to offline until the heartbeat stops.

**Describe alternatives you've considered**

The internal Docker probe goes a long way to make this feature almost unnecessary but the issue is having to setup monitors both on internal monitoring and in OneUptime.

**Additional context**

Check out other uptime monitor or status page product features related to "passive" or "heartbeat" or "cron" monitoring for similar ideas.

**Comment by TobiasGrether** [comment]
This would be super useful and would help #530

**Comment by Kashalls** [comment]
This would be a great feature as this is often a sought after feature. 

The custom probes does not really work for us as that just provides another failure point and another container to maintain (excluding the fact that the container image is hosted on Docker Hub (which is a different discussion)). 

It would be so much easier to setup a simple cronjob that executes every 5 minutes to call out a url like `https://oneuptime.com/heartbeat/<uuid>/<heartbeat uuid>` as that just simply relies on the host being up and connected to the internet. Very useful for homelabbers to tell if their router is connected to the internet or if their Secondary WAN is still up. 

An example of use in production would be to hook into [Prometheus](https://prometheus.io/)'s Alert Manager, which is usually found on many kubernetes clusters. Using the alert manager config to setup a reciever for the watchdog event which lets you know that alert manager is still running and maybe emitting other events you might be interested in.

**Comment by simlarsen** [comment]
Affirmitive. Already in acitve development. Out in a week from now.

**Comment by simlarsen** [comment]
This is released. Please update to latest or use SaaS servicve
