### ISSUE TITLE
Page crash on editing Scheduled Maintenance

### ISSUE THREAD

**Issue by lauw70** [OneUptime/oneuptime#495]
**Describe the bug**
The page crashes (white screen) when editing a Scheduled Maintenance Event.

**To Reproduce**
1. Create a monitor
2. Create a status page on which you show the monitor
3. Create a Scheduled Maintenance Event for the monitor
4. Open the Event.
5. Click "Edit Scheduled Maintenance Event"
6. Page crashes milliseconds after showing the popup

**Expected behavior**
Being able to edit the Event

**Screenshots**
![image](https://github.com/OneUptime/oneuptime/assets/11587991/b10492e5-dc52-4bd3-b300-1effea2c3cf1)

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Chrome

**Additional context**
This is the second bug I'm reporting in 12h by simply testing out the app. In both cases the entire app crashed showing a white screen because of an uncaught exception. Both could've been caught by typechecking.

**Comment by nzdhandala** [comment]
Thank you for reporting. Fixed: https://github.com/OneUptime/oneuptime/commit/72635b8c8f429c7cd7d1606e48d31657092aaf4b. Deploy in 1 hour.

**Comment by lauw70** [comment]
@nzdhandala thanks for the quick fixes
