### ISSUE TITLE
configure.sh: line 190: ts-node-esm: command not found | DEBIAN 11.7

### ISSUE THREAD

**Issue by Clashplayer-PROTECT** [OneUptime/oneuptime#496]
Hello,
When I run the "bash install.sh" command, the script freezes and gives me the following error: 
root@S-ONEUPTIME:~/oneuptime# bash install.sh
hint: Pulling without specifying how to reconcile divergent branches is
hint: discouraged. You can squelch this message by running one of the following
hint: commands sometime before your next pull:
hint:
hint:   git config pull.rebase false  # merge (the default strategy)
hint:   git config pull.rebase true   # rebase
hint:   git config pull.ff only       # fast-forward only
hint:
hint: You can replace "git config" with "git config --global" to set a default
hint: preference for all repositories. You can also pass --rebase, --no-rebase,
hint: or --ff-only on the command line to override the configured default per
hint: invocation.
Already up to date.
Welcome to the OneUptime 🟢 Runner

Please enter your sudo password now:

Thanks! 🙏

Ok! We'll take it from here 🚀
Making sure any stack that might exist is stopped
Grabbing latest apt caches
Hit:1 http://security.debian.org/debian-security bullseye-security InRelease
Hit:2 http://deb.debian.org/debian bullseye InRelease
Hit:3 http://deb.debian.org/debian bullseye-updates InRelease
Hit:4 http://deb.debian.org/debian bullseye-backports InRelease
Hit:5 https://download.docker.com/linux/debian bullseye InRelease
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
All packages are up to date.
Installing OneUptime 🟢
hint: Pulling without specifying how to reconcile divergent branches is
hint: discouraged. You can squelch this message by running one of the following
hint: commands sometime before your next pull:
hint:
hint:   git config pull.rebase false  # merge (the default strategy)
hint:   git config pull.rebase true   # rebase
hint:   git config pull.ff only       # fast-forward only
hint:
hint: You can replace "git config" with "git config --global" to set a default
hint: preference for all repositories. You can also pass --rebase, --no-rebase,
hint: or --ff-only on the command line to override the configured default per
hint: invocation.
Already up to date.

changed 19 packages in 6s
SSL Certificate exists. Skipping generating a new one.
configure.sh: line 190: ts-node-esm: command not found
root@S-ONEUPTIME:~/oneuptime#

**Comment by nzdhandala** [comment]
Can you please pull latest release and rerun it should now be fixed.

**Comment by Antonyrahul** [comment]
Hello @nzdhandala i have pulled the latest and i am still running into this error . OS: ubuntu 20.4

**Comment by CodeMeZone** [comment]
> Hello @nzdhandala i have pulled the latest and i am still running into this error . OS: ubuntu 20.4

Same here. 


```
# lsb_release -a
Distributor ID: Ubuntu
Description:    Ubuntu 22.04.2 LTS
Release:        22.04
Codename:       jammy
```

**Comment by nzdhandala** [comment]
Let me see if there's anything I can do to fix it.

**Comment by CodeMeZone** [comment]
> Let me see if there's anything I can do to fix it.

`configure.sh: line 193: ts-node-esm: command not found
`
for  Ubuntu 22.04

**Comment by Halllo5** [comment]
I had the same error but it seems like after a reboot it worked for me without a problem

**Comment by CodeMeZone** [comment]
> I had the same error but it seems like after a reboot it worked for me without a problem

This isn't really helpful, what OS?

**Comment by Halllo5** [comment]
> > I had the same error but it seems like after a reboot it worked for me without a problem
> 
> This isn't really helpful, what OS?

Sorry, i have updated the comment with more info's

**Comment by Clashplayer-PROTECT** [comment]
Hello, Did you push?

**Comment by gap579137** [comment]
A quick reboot fixed it for me as well. Unsure of the actual issue but at least there is a quick work around for now.
