### ISSUE TITLE
Custom domain not working

### ISSUE THREAD

**Issue by JanRajnoha** [OneUptime/oneuptime#497]
**Describe the bug**
Custom domain not working with cloudflare -> Invalid SSL certificate and status code 526

**To Reproduce**
1. Added custom domain [https://status.janrajnoha.cz](https://status.janrajnoha.cz) 
2. Added CNAME for status and value live-something something (on phone I could not see this part of system, precise page will be updated) 
3. Result could be seen on that subdomain. I waited several hours, other tools worked instantly

**Expected behavior**
It will work

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser Edge Canary

**Smartphone (please complete the following information):**
 - Device: Android
 - OS: 13
 - Browser Edge canary

**Additional context**
-

**Comment by nzdhandala** [comment]
Some DNS requests take time to propogate. Please wait 24 hours and if this does not resolve by then, feel free to re-open this issue.

**Comment by JanRajnoha** [comment]
It is working 🤦‍♂️, I didn't see this error message before so I have been a little confused.
