### ISSUE TITLE
Domain verification: Server Error

### ISSUE THREAD

**Issue by lauw70** [OneUptime/oneuptime#498]
**Describe the bug**

Click on "Verify domain" returns a server error.

**To Reproduce**
1. Create a custom domain.
2. Add txt record to nameserver.
3. Click "Verify Domain".
4. See "Server Error" (server returns 500)

**Expected behavior**
The domain to be verified

**Screenshots**
![server error](https://github.com/OneUptime/oneuptime/assets/11587991/1f22a8d8-84e6-4bd7-86ff-f01d3c966b30)

**Desktop (please complete the following information):**
 - OS: macos
 - Browser: Chrome

**Comment by nzdhandala** [comment]
Just checked and your domain is verified.
