### ISSUE TITLE
Getting Server Error

### ISSUE THREAD

**Issue by rajasivaxx** [OneUptime/oneuptime#499]
When trying to self host getting the below error when trying to register an account !!

![image](https://github.com/OneUptime/oneuptime/assets/58806010/08dc5a90-f559-4ef1-8e4b-d44d98b75aa7)

**Comment by nzdhandala** [comment]
Closing this issue because of no logs

**Comment by rajasivaxx** [comment]
> Closing this issue because of no logs

Please find the below logs !!

![image](https://github.com/OneUptime/oneuptime/assets/58806010/638dfb74-d133-49ca-88ea-09157ec61cf5)

**Comment by rajasivaxx** [comment]
We just followed the instructions from Readme file is there anything we need to change after bash install.sh !!

**Comment by gap579137** [comment]
I am getting the same issue...
