### ISSUE TITLE
Unable to connect to workflow server

### ISSUE THREAD

**Issue by rajasivaxx** [OneUptime/oneuptime#500]
Unable to connect to workflow server and checked the logs we got postgress authentication failed error.

![image](https://github.com/OneUptime/oneuptime/assets/58806010/072c0650-7596-4839-a3ff-9155f9027369)

**Comment by nzdhandala** [comment]
Unfortunately, wont be able to help since this is OSS install. Every env is different and we're unable to replicate this issue.
