### ISSUE TITLE
Cant configure Email with OCI Email delivery

### ISSUE THREAD

**Issue by Halllo5** [OneUptime/oneuptime#503]
**Describe the bug**
When configuring SMTP with the below shown configuration (OCI Email Delivery) no emails are sent and the following error appears in the notification container 
Down below i have pasted the configuration and the error.
**To Reproduce**
1. Configure SMTP with OCI Email Delivery

**Expected behavior**
A Email should be sent :)

**Additional context**
Configuration: 
```env
SMTP_USERNAME='MyUsername'
SMTP_PASSWORD='MyPassword'
SMTP_PORT=587 #or 25 both result in the same error
SMTP_EMAIL=uptime@example.com
SMTP_FROM_NAME=OneUptime
SMTP_IS_SECURE=true
SMTP_HOST='smtp.email.<Location>.oci.oraclecloud.com'
```
Error:
```
{
  message: 'Unhandled rejection in server process occurred',
  level: 'error',
  timestamp: '2023-06-27T13:34:32.552Z'
}
{
  library: 'SSL routines',
  reason: 'wrong version number',
  code: 'ESOCKET',
  command: 'CONN',
  level: 'error',
  message: 'B8BB5142457F0000:error:0A00010B:SSL routines:ssl3_get_record:wrong version number:../deps/openssl/openssl/ssl/record/ssl3_record.c:354:\n',
  stack: 'Error: B8BB5142457F0000:error:0A00010B:SSL routines:ssl3_get_record:wrong version number:../deps/openssl/openssl/ssl/record/ssl3_record.c:354:\n',
  timestamp: '2023-06-27T13:34:32.552Z'
}
{
  message: Promise {
    <rejected> [Error: B8BB5142457F0000:error:0A00010B:SSL routines:ssl3_get_record:wrong version number:../deps/openssl/openssl/ssl/record/ssl3_record.c:354:
    ] {
      library: 'SSL routines',
      reason: 'wrong version number',
      code: 'ESOCKET',
      command: 'CONN',
      level: 'error',
      [Symbol(level)]: 'error'
    }
  },
  level: 'error',
  timestamp: '2023-06-27T13:34:32.552Z'
}
```

**Comment by Kashalls** [comment]
@Halllo5 I would check this out: https://github.com/nodemailer/nodemailer/issues/1461

Nodemailer is used as the underlying mail sender, they recommend you turn secure to false. It just means it first trys to send as a clear text, the smtp server will upgrade the connection to use TLS.

An alternative issue to this would be that the package needs to be updated to its latest version.

**Comment by Halllo5** [comment]
It seems to work when setting secure to false.

Thank you so much @Kashalls
