### ISSUE TITLE
Custom HTTP parameters for Cloudflare Access are not working

### ISSUE THREAD

**Issue by HaukeMarquardt** [OneUptime/oneuptime#504]
Hi!

**Describe the bug**
I am trying to bypass Cloudflare Access using custom header parameters in my GET request. (https://developers.cloudflare.com/cloudflare-one/identity/service-tokens/)
For some reason this does not work with OneUptime. I can see the Cloudflare Access HTML in the response body in the status timeline.

**To Reproduce**
1. Add an API monitor to a destination which is protected by Cloudflare Access.
2. Add the service token to the custom header parameters (CF-Access-Client-Id, CF-Access-Client-Secret) of the monitor
3. See the results

**Expected behavior**
If the header parameters are set correctly, the response should be the response from your API.

The token is valid. I've already deployed a few self-hosted status tools that use the same token.

**Comment by simlarsen** [comment]
```
{
oneuptime-test-server-1  |   message: {
oneuptime-test-server-1  |     accept: 'application/json',
oneuptime-test-server-1  |     'access-control-allow-origin': '*',
oneuptime-test-server-1  |     'content-type': 'application/json;charset=UTF-8',
oneuptime-test-server-1  |     cf_key: 'ABC',
oneuptime-test-server-1  |     cf_name: 'HELLO',
oneuptime-test-server-1  |     'user-agent': 'axios/0.26.1',
oneuptime-test-server-1  |     host: '192.168.1.28:3800',
oneuptime-test-server-1  |     connection: 'close'
oneuptime-test-server-1  |   },
oneuptime-test-server-1  |   level: 'info',
oneuptime-test-server-1  |   timestamp: '2023-08-02T17:24:04.939Z'
oneuptime-test-server-1  | }
```

**Comment by simlarsen** [comment]
Headers are successfully being sent.

**Comment by simlarsen** [comment]
Can you please test this again and reopen if it does not work.
