### ISSUE TITLE
Account Creation: International phone numbers deemed invalid due to length

### ISSUE THREAD

**Issue by MarioLiebisch** [OneUptime/oneuptime#505]
**Describe the bug**
I tried to setup a cloud account to test the service, but had to lie/fake the phone number field, as our actual German business phone number didn't pass the validity test, as it's deemed to be too long (which it isn't. according to standards).

**To Reproduce**
1. Start [creating an account](https://oneuptime.com/accounts/register)
2. Try entering a longer German telephone number in international notation: `+4911112222222` (1s = area code, 2s = local number)
3. Move to he next input field and observe the number being deemed invalid

**Expected behavior**
The phone number should be accepted, even if it's longer than a typical US number, as long as it satisfies ITU-T E.164.

**Screenshots**
![Screenshot](https://github.com/OneUptime/oneuptime/assets/1854245/8fb49544-6137-47f3-8538-ec0dbbaf267f)

**Additional context**
OneUptime currently follows ITU-T E.123, which uses the US 3-3-4 format.
This won't work for some international numbers, like many German ones, as the area code might consist of up to 4 digits ([ITU-T E.164](https://en.wikipedia.org/wiki/E.164) allows up to 15 digits total, compared to E.123's 12 digits)

**Comment by nzdhandala** [comment]
Fixed. https://github.com/OneUptime/oneuptime/pull/501/commits/3d3bf1d092840ba2aa279c66b6632da66e527e99 Will be deployed end of the day today.
