### ISSUE TITLE
Update profile picture button is missing.

### ISSUE THREAD

**Issue by bigelio** [OneUptime/oneuptime#524]
**Describe the bug**
Update profile picture button is missing.
**To Reproduce**
1. Go to https://oneuptime.com/dashboard/user-profile/profile-picture
2. Click on **profile picture**
3.  No call to action button for updating the user profile picture
**Expected behavior**
User should be able to update his/her profile picture

**Screenshots**
<img width="1440" alt="Screenshot 2023-07-15 at 19 43 44" src="https://github.com/OneUptime/oneuptime/assets/70667354/bfdd3b58-c610-47d4-ab80-7b9d10217976">

**Additional context**
No.

**Comment by simlarsen** [comment]
Its visible: 

<img width="2532" alt="image" src="https://github.com/OneUptime/oneuptime/assets/104437376/a28b9ac4-b337-4712-8f8c-cad0b566863e">
