### ISSUE TITLE
Remote Probe Executors

### ISSUE THREAD

**Issue by TobiasGrether** [OneUptime/oneuptime#530]
**Is your feature request related to a problem? Please describe.**
Currently, it is not possible (except when running self-hosted) to monitor the status of internal systems without exposing them to the public to be reachable by the oneuptime servers.

**Describe the solution you'd like**
 It would be nice to have a small container that one can run in their internal network to proxy probe pings. This could be done the following way:
- Set up a new "Remote Probe Executor" in the UI
- UI gives you a unique, 32 character long key
- You start up the docker container with the given key
- You assign certain monitors to go through this executor
The actual executor would be super simple to implement.

**Describe alternatives you've considered**
Selfhosting, but its not feasible for some.

**Additional context**

**Comment by TobiasGrether** [comment]
I just found this to be already implemented under a different name

**Comment by Kashalls** [comment]
> I just found this to be already implemented under a different name

What are you referring to "under a different name?"

**Comment by simlarsen** [comment]
Cusom Probes. Should be under Project Settings.
