### ISSUE TITLE
Option to reverse Scheduled Maintenance Update Order

### ISSUE THREAD

**Issue by tankerkiller125** [OneUptime/oneuptime#532]
**Is your feature request related to a problem? Please describe.**
Currently the Scheduled Maintenance has the latest information at the bottom, which makes perfect sense maybe when your viewing just one maintenance item. But on the main page, and the overview page I would argue that reversing the order (so the newest info is on top) makes the most sense.

**Describe the solution you'd like**
Either the default to be changed, or an option made available to reverse the order in which scheduled update information is displayed to users. In particular on the overview page. The individual scheduled maintenance item page should still display oldest to newest.

**Comment by simlarsen** [comment]
I think we only show the latest state and note on the main page. We dont show all the notes and states on the overview page.

**Comment by simlarsen** [comment]
tagged it as wontfix, but let me know if that's not the case and I'll be happy to re-open this for you.

**Comment by tankerkiller125** [comment]
> I think we only show the latest state and note on the main page. We dont show all the notes and states on the overview page.

This is not the case from what I experienced (which is why I reported any issue at all, otherwise I would have been fine with that too).

What I'm seeing is all of the Scheduled Maintenance notes get pushed to the main page. Not just the newest one.

**Comment by simlarsen** [comment]
Fixed it: https://github.com/OneUptime/oneuptime/commit/26a4ba606e5750a4eff5a0a52688ba004a57d07a 

Should be deployed by end of today.
