### ISSUE TITLE
Push Containers To GHCR.io

### ISSUE THREAD

**Issue by Kashalls** [OneUptime/oneuptime#554]
**Is your feature request related to a problem? Please describe.**
Docker Hub provides a very restrictive rate limit for anonymous users at 100 pulls every 6 hours per ip.
For authenticated users, its 200 pulls every 6 hours per ip.
Paid Users can get up to 5000 pull a day.

We as a community would very much appreciate mirroring the packages to ghcr.io, githubs package platform, as it offers better if not non-existant ip ratelimits.

**Describe the solution you'd like**

Please change workflows to also push containers to ghcr.io/oneuptime/container

**Describe alternatives you've considered**

Users can mirror the packages themselves through some painful and confusing steps of forking the repo, modifying the workflows to update the container image tag every so often and deploy a container.

**Additional context**
https://docs.docker.com/docker-hub/download-rate-limit/

**Comment by onedr0p** [comment]
This would be great 👍

**Comment by simlarsen** [comment]
GHCR_TOKEN has been added as an env var for this. Feel free to send a PR if you are implementing this.

**Comment by Kashalls** [comment]
> GHCR_TOKEN has been added as an env var for this. Feel free to send a PR if you are implementing this.

Adding that token is kind of redundant. If you go to https://github.com/oneuptime/oneuptime/settings/actions, at the bottom, you can select `Read and write permissions` for workflow permissions. Setting a static env variable isn't recommended. GITHUB_TOKEN is deleted and created every time a workflow finishes and starts.

**Comment by simlarsen** [comment]
<img width="893" alt="image" src="https://github.com/OneUptime/oneuptime/assets/104437376/ebef6731-f482-4d3e-a830-dc6a329854d6">

Feel free to not use that var and I can remove it if we're not using it.
