### ISSUE TITLE
UI/UX: A disabled monitor should not show up as having an operational status

### ISSUE THREAD

**Issue by onedr0p** [OneUptime/oneuptime#562]
**Is your feature request related to a problem? Please describe.**

A disabled monitor should not show up as having an operational status

**Describe the solution you'd like**

Monitor Status should report state Disabled (not Operational) if not enabled or only shown in the Disabled Monitors page

**Describe alternatives you've considered**

**Additional context**

**Comment by simlarsen** [comment]
Fixed in master. Will be deployed EOD today.
