### ISSUE TITLE
CommonServer does not support sslsecured databases.

### ISSUE THREAD

**Issue by Kashalls** [OneUptime/oneuptime#572]
https://github.com/OneUptime/oneuptime/blob/master/CommonServer/Infrastructure/PostgresConfig.ts#L16
https://github.com/OneUptime/oneuptime/blob/master/CommonServer/Infrastructure/PostgresDatabase.ts#L38

Connecting to a managed postgres database provider requires you to have sslmode set to require.
The current code does not allow for it to be set.

See [data-source-options for typeorm](https://typeorm.io/data-source-options#postgres--cockroachdb-data-source-options).

Proposed change would be to check to see if `process.env.DATABASE_CERT` or `process.env.DATABASE_KEY` or `process.env.DATABASE_CA` and set it in the ssl object.

**Comment by simlarsen** [comment]
Feel free to implement this change.
