### ISSUE TITLE
UI/UX: Navigation Bar disappears on non-desktop resolutions

### ISSUE THREAD

**Issue by Kashalls** [OneUptime/oneuptime#575]
**Describe the bug**
Navigation bar to swap from home to monitors and etc is gone on lower resolution screens.

**To Reproduce**
Open app, sign in. stuck on home.

**Expected behavior**
Navigation should be available through some kind of hamburger menu

**Screenshots**
![image](https://github.com/OneUptime/oneuptime/assets/17620516/42795878-ecd2-42d6-b52a-85377a225df6)
![image](https://github.com/OneUptime/oneuptime/assets/17620516/c17ae9ed-972a-49ce-b102-ca49e6d0abd5)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Chrome & Firefox
 - Version: 155.0.3

**Smartphone (please complete the following information):**
 - Device: Pixel 6 Pro
 - OS: Android 13
 - Browser Chrome and Firefox
 - Version: 155

**Comment by simlarsen** [comment]
Fixed: https://github.com/OneUptime/oneuptime/commit/baec3734aae46aed947bee2c168cab7e686028ea. Deploy by EOD today.
