### ISSUE TITLE
Heartbeat Monitors: Monitoring Interval shows "No interval defined"

### ISSUE THREAD

**Issue by Kashalls** [OneUptime/oneuptime#583]
**Describe the bug**
Heartbeat monitors currently show two pages, criteria and interval. You should be able to set the interval on the interval page.
It currently is only editable through the criteria page.

**To Reproduce**
1. Create a heartbeat monitor
2. View the newly created monitor
3. View its interval

**Expected behavior**
You should be able to configure the interval here of how long oneuptime expects this to fire.

**Screenshots**
![image](https://github.com/OneUptime/oneuptime/assets/17620516/c65b945d-de87-4fce-b6e1-1d37dfb24dde)
![image](https://github.com/OneUptime/oneuptime/assets/17620516/ff56fd70-e7c9-4312-9649-4734e9db6fcf)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Firefox
 - Version 115

**Smartphone (please complete the following information):**
 - Device: Pixel 6 Pro
 - OS: Android 13
 - Browser Firefox
 - Version 115

**Comment by simlarsen** [comment]
Ths should be fixed. Please update to latest
