### ISSUE TITLE
Status page headers are not ordered by the order configured in the UI

### ISSUE THREAD

**Issue by amatsoukas** [OneUptime/oneuptime#587]
**Describe the bug**
The Status page headers are not ordered by the order configured in the UI, but they are ordered by the createdAt value in the database instead. Changing the order from the dashboard, does not change the order on the status page.

**Comment by simlarsen** [comment]
You mean monitors on staus page?

**Comment by simlarsen** [comment]
This should be fixed fast.

**Comment by simlarsen** [comment]
Fixed! should be deployed EOD today. https://github.com/OneUptime/oneuptime/commit/6828db8fc96f6c1157c1148cfc11d6af4102c542
