### ISSUE TITLE
Redirect: After logging into one-time account does not push to one uptime project

### ISSUE THREAD

**Issue by alanredfordhayes** [OneUptime/oneuptime#696]
**Describe the bug**
A user will click their okta tile to login to a one uptime project.
One uptime will send a banner and ask the user to login to their account. 
A user will log into their one uptime account using their email and password.
A banner with a button will appear that asks the user to reload and use SSO login. 
The button does push the user into the one uptime project.
The user must exit the browser tab and go back to okta to use the okta tile.

**To Reproduce**
Set up an sso application in okta
A new one uptime project 
add new users to okta. 
have the user use the okta tile.

**Expected behavior**
To be fair, we expect a user to be provisioned into oneuptime and go directly to the project without any action by the user.
Having to login to your one uptime account is not ideal. However that appears to be a design issue.  The bug is after logging into the one uptime account you should be redirected into the one uptime project that has sso enabled. 

**Screenshots**

Repeated with Simon Larson

**Desktop (please complete the following information):**
 - OS: MacOs
 - Browser Safari 16.6, Chrome 115.0.5790.170 

**Smartphone (please complete the following information):**

**Additional context**

**Comment by simlarsen** [comment]
Fixed: https://github.com/OneUptime/oneuptime/commit/a5a6b05b807e93c3dc7771a0199d02b091fa1466 

Deploy by EOD today
