### ISSUE TITLE
No way to create a local account?

### ISSUE THREAD

**Issue by JesseWebDotCom** [OneUptime/oneuptime#699]
Trying to test out a local instance of OneUptime. Successfully installed and viewing http://ip_address/accounts but I don't see an option to create a local account (I want this solution and its dependencies completely local).

Is this not possible?  BTW - I have also not configured and do not plan to configure email for this environment (if that matters).

**Comment by simlarsen** [comment]
@JesseWebDotCom you should have sign up page where you can create your account. Did you try to sign up?

**Comment by JesseWebDotCom** [comment]
I did and was able to figure it out but my issue is email is required for OneUptime account creation:
- username: the form asks for an email and I'm assuming requires email format.
- account verification: verification links are emailed to the user's email address. this makes it a requirement to enable email in OneUptime.

So I had to:
- create the account with an email address (maybe it didn't need to be a valid address - perhaps I could have entered me@no.local)
- run "docker logs one-time-notification-1", find the tokenVerifyUrl" and click on it.

OneUptime knows I do not have email setup and yet tried to send an email verification and left me with no clear way to validate the new account. I guess the ideal would instant verification upon creation when email is not enabled or better yet - an option for non verifiable accounts like local accounts

**Comment by simlarsen** [comment]
Nice suggestion! Will implement this as well.

**Comment by simlarsen** [comment]
Fixed: https://github.com/OneUptime/oneuptime/commit/8a18e8beebdfa346c7e10b8ccb790fa73e1ac938

**Comment by simlarsen** [comment]
Will release by end of the day today
