### ISSUE TITLE
{"error":"Server Error"} trying to access https://oneuptime.com/reference/email-log

### ISSUE THREAD

**Issue by JesseWebDotCom** [OneUptime/oneuptime#701]
I get **{"error":"Server Error"}** trying to access https://oneuptime.com/reference/email-log

Linked from this page:
https://oneuptime.com/reference/introduction

**Comment by simlarsen** [comment]
Fixed: https://github.com/OneUptime/oneuptime/commit/cfb8edfab37a7ddfc2c8d27cf315e04ced59c4bd 

Deploy by EOD today
