### ISSUE TITLE
"Connect Slack to OneUptime using Workflows" YouTube video is outdated/incorrect

### ISSUE THREAD

**Issue by JesseWebDotCom** [OneUptime/oneuptime#702]
Following this YouTube video (which is great, thank you) is outdated/incorrect:
https://www.youtube.com/watch?v=VX3TwFrpvyI

Here are the changes required to send a message based on an incident trigger (the first manual web hook test works fine):
1) in the ""On create incident" trigger, you have to select set this in the "Select Fields":
{"title": true}

2) In the "Send Message to Channel" component, you need to use this variable in the message text field:
{{local.components.incident-on-create-1.returnValues.model.title}}

**Comment by simlarsen** [comment]
New Video: https://youtu.be/k1-reCQTZnM
