### ISSUE TITLE
Ability to send fancy slack messages

### ISSUE THREAD

**Issue by JesseWebDotCom** [OneUptime/oneuptime#704]
Right now the "Send message to Channel" is text with minimal formatting.  Ideally you support slack message blocks:
https://api.slack.com/messaging/webhooks#advanced_message_formatting

or minimally (but not ideal) sent all messages in a slack message block with text type markdown so we can use markdown to format our messages.

**Comment by simlarsen** [comment]
Fixed: https://github.com/OneUptime/oneuptime/pull/734

**Comment by simlarsen** [comment]
I've added it as markdown for now. Please let me know if this works for you and if this does not, feel free to create another issue.

**Comment by simlarsen** [comment]
Release EOD tomorrow.
