### ISSUE TITLE
Unable to include incidentSeverity.name in workflow

### ISSUE THREAD

**Issue by JesseWebDotCom** [OneUptime/oneuptime#705]
I want to include the name of the incident severity in a workflow message I send to slack. I was able to send the title and description (and even the incident severity entity object) to slack using this in the select field of the "on create incident" component:

{"title": true, "description": true, "incidentSeverity: true}

incident severity shows as [object Object] in the slack message.

In the logs, I see the incidentSeverity object with its _id field.

How can I select the incidentSeverity name and then include it in the slack message (unless its currently not possible)?

**Comment by simlarsen** [comment]
Try: 

```
{"title": true, "description": true, "incidentSeverity: {"name": true}}
```

**Comment by JesseWebDotCom** [comment]
That worked perfectly, thanks!
