### ISSUE TITLE
Add ids to key HTML elements

### ISSUE THREAD

**Issue by JesseWebDotCom** [OneUptime/oneuptime#707]
ex. with custom css, I'd like to hide the html div that shows incidents on status pages but do not hide announcements.

right now, this example is not possible without some advanced css targeting (if possible at all)

**Comment by simlarsen** [comment]
@JesseWebDotCom which div? Can you please send me the screenshot. I can do a quick PR and add an id.

**Comment by simlarsen** [comment]
Fixed here: https://github.com/OneUptime/oneuptime/commit/e1f697c57f1938253a20310902801b317ddb2129 

Feel free to re-open this if this does not work for you. 

Deploy to SaaS by EOD today.

**Comment by JesseWebDotCom** [comment]
Thanks - forgot to reply (I am not allowed to send out screenshot / data from the eval I am building). I will test once this is deployed.  Thanks again - really enjoying this product so far (you'll probably see a lot more issues/requests form me as the eval grows and I expand to test users).
