### ISSUE TITLE
Website and API monitors require HEAD  / Logging is lacking

### ISSUE THREAD

**Issue by JesseWebDotCom** [OneUptime/oneuptime#710]
Discovered that the website and API monitors require HEAD. I didn't see a mention of this anywhere. I have internal API's that only use GET and POST. If I do not enable HEAD in my API, OneUptime will make a HEAD request and get a 403. When checking the monitor logs, I see the 403 error but no mention of the REST method used. It is had logged that it failed with a HEAD request, I would have immediately known how to fix.

My suggestion:
- add the REST method you use to logging
- optionally - if HEAD method fails, try the GET or POST anyway.

**Comment by simlarsen** [comment]
Fixed here: https://github.com/OneUptime/oneuptime/commit/36746412244df96821713ca5a94384cc1e781afc
