### ISSUE TITLE
Status page title

### ISSUE THREAD

**Issue by JesseWebDotCom** [OneUptime/oneuptime#712]
I don't see a way to display a title next to the status page logo. I see how I can add an SEO title (which doesn't get display on the page), I see how I can fake a title in the Essential Branding Overview Page Description using markdown, I see how I can add header links - but I can't find how I display a title to go next to my status page logo.

**Comment by simlarsen** [comment]
Ideally add the text in the image of the logo and upload to fix this issue.

**Comment by JesseWebDotCom** [comment]
This is not desirable as now every product "team" / owner will need to have graphics software, skills, etc - as opposed to finding a desired image and typing the title they want.
