### ISSUE TITLE
Disabling status page subscribe should hide subscription tab

### ISSUE THREAD

**Issue by JesseWebDotCom** [OneUptime/oneuptime#715]
Why keep the subscribe tab, allow users to click on it, present them with a form. have them enter their emails address and then click subscribe to just be presented with an error of "Subscribers not enabled for this status page". Why not just hide the subscribe tab?

**Comment by simlarsen** [comment]
Fixed. https://github.com/OneUptime/oneuptime/commit/68ca9af88c2c40dc2ac28f44041cfc859ea59241
