### ISSUE TITLE
Add HTML ID's to status page tabs

### ISSUE THREAD

**Issue by JesseWebDotCom** [OneUptime/oneuptime#716]
Thanks for [adding IDs to sections in the status page](https://github.com/OneUptime/oneuptime/issues/707). Can you add for each of the tabs of the status page?  For example, I want to hide the subscribe tab but it doesn't have an ID so I can't use CSS to set its display to none.

**Comment by simlarsen** [comment]
Done! Will be deployed by end of the day today
