### ISSUE TITLE
UI and API to manage projects and above

### ISSUE THREAD

**Issue by JesseWebDotCom** [OneUptime/oneuptime#717]
I don't see UI options and or API calls to manage projects and above items like users, maybe server settings, etc.

would be nice to be able to do things like:
- check for duplicate monitors across projects
- check for aggressive monitors (ex. monitor every minute)
- check for excessive number of monitors per project
- programmatically create a project
- etc

**Comment by simlarsen** [comment]
@JesseWebDotCom  Nawaz asked me to work on this on priority. You can follow progress here: https://github.com/OneUptime/oneuptime/pull/746

**Comment by simlarsen** [comment]
@JesseWebDotCom we have launched admin-dashboard, we're now working on admin level API's once we have that, will let you know and mark this issue as complete.

**Comment by JesseWebDotCom** [comment]
Awesome, thanks

**Comment by simlarsen** [comment]
The API  is done as well. You should now be able to set API Key on Admin Dashboard and use Project and User level API's. This will be released to docker tomorrow.
