### ISSUE TITLE
Please allow use of M365 Direct Send in custom SMTP config

### ISSUE THREAD

**Issue by GarethDMobysoft** [OneUptime/oneuptime#718]
**Is your feature request related to a problem? Please describe.**
Hi team - I have another issue with SMTP set up - can you please offer an option for no authentication?  We use M365 and we can use the smarthost from any email address with our domain even that is has no mailbox ([https://learn.microsoft.com/en-us/exchange/mail-flow-best-practices/how-to-set-up-a-mu[…]application-to-send-email-using-microsoft-365-or-office-365]([](https://learn.microsoft.com/en-us/exchange/mail-flow-best-practices/how-to-set-up-a-multifunction-device-or-application-to-send-email-using-microsoft-365-or-office-365#option-2-send-mail-directly-from-your-printer-or-application-to-microsoft-365-or-office-365-direct-send))) the modal for adding an SMTP config unfortunately doesn't allow us to move on without entering credentials.

**Describe the solution you'd like**
An option to use no authentication as a start (with a list of IPs that are sending OneUptime email so I can populate my SPF record)

**Comment by simlarsen** [comment]
Fixed: https://github.com/OneUptime/oneuptime/commit/27f5f96ba99dc15a092fa95e138426b4d2efe6d3
