### ISSUE TITLE
Backend server monitoring and HA

### ISSUE THREAD

**Issue by JesseWebDotCom** [OneUptime/oneuptime#720]
What is the design for / current implementation if any for:
1) monitoring of the backend server
2) redundancy of the backend server

For example, my backend server disk filled and OneUptime was inaccessible. Ideally there would be a solution to a) notify when that happens and b) have another backend server pickup where the first one left off.

**Comment by simlarsen** [comment]
You can use docker swarm for HA. We have a docker compose file that you can convert into docker stack.
