### ISSUE TITLE
Display total uptime percentage for every monitor and a global one if possible

### ISSUE THREAD

**Issue by hugomn** [OneUptime/oneuptime#722]
**Is your feature request related to a problem? Please describe.**
No. It's a new and simple feature.

**Describe the solution you'd like**
Other status pages tools display a % of the uptime for the whole period of 90 days. Currently we can only see the % of uptime for one day.

**Additional context**
Check how other platforms display the % of uptime:
<img width="810" alt="Screenshot 2023-08-19 at 12 18 32" src="https://github.com/OneUptime/oneuptime/assets/497957/5b683832-4e85-4ca2-a2ab-90b62d8602f7">

This is what we have today in OneUptime:
<img width="982" alt="Screenshot 2023-08-19 at 12 19 21" src="https://github.com/OneUptime/oneuptime/assets/497957/4dd2e49a-bd37-467e-afd0-56cb4c5c89dd">

It would also be nice to have a global % uptime considering all monitors.

**Comment by simlarsen** [comment]
Nice idea, should be launched by end of next week.

**Comment by hugomn** [comment]
@simlarsen any updates on this? Thanks!

**Comment by simlarsen** [comment]
@hugomn this is a little more complicated than we originally thought BUT it should be out by end of Oct.

**Comment by simlarsen** [comment]
This is done! @hugomn

**Comment by hugomn** [comment]
Amazing, thanks @simlarsen! When will it be available on the free plan of the host solution?

**Comment by simlarsen** [comment]
It's available.

**Comment by hugomn** [comment]
@simlarsen do I need to enable or setup something to enable it? I cannot see it here: https://oneuptime.com/status-page/fbf6c35f-9703-414d-b08f-b001bfd0bcdd

**Comment by hugomn** [comment]
> It's available.

I've found the settings to enable it. Thanks!
