### ISSUE TITLE
BUG - Website monitoring over non standard port will not work

### ISSUE THREAD

**Issue by VA2XJM** [OneUptime/oneuptime#724]
**Describe the bug**
When monitoring a URL using the `website` monitor that contain a port inside the URL, the monitor will go offline.

**To Reproduce**
1. Create a `website` type monitor and indicate a URL with a port (ex: http://my_domain.tld:8080/index.html )
2. Use default settings and set monitoring every minute
3. Finish and wait for monitor to become offline
4. See error : `Monitor is offline. Parse Error: Expected HTTP/`

**Expected behavior**
The request should go and be executed as usual.

**Additional context**
The error message is incomplete, but I have the feeling that there is some sanity checks that generate this error message.

Testing using oneuptime.com account.

**Comment by VA2XJM** [comment]
@simlarsen : `081b2080-f101-4dba-b8b7-7236f2ea1dbd`

**Comment by simlarsen** [comment]
Fixed: https://github.com/OneUptime/oneuptime/commit/df65490d4abf7ce064384a9df157d74895329285 

Should be deployed to oneuptime.com end of today
