### ISSUE TITLE
Improvement: Create New Incident Template: Incident Severity should be optional in template

### ISSUE THREAD

**Issue by ThoSt81** [OneUptime/oneuptime#726]
When creating a new template you have to select an _Incident Severity_.
This field should be optional in the template (same as _Monitors affected_ and _Change Monitor Status to_).

**Comment by simlarsen** [comment]
Fixed: https://github.com/OneUptime/oneuptime/pull/728/commits/6bc9e9743306b987579072900d4e5bb7fcc57eea 

Will be deployed today.
