### ISSUE TITLE
Create New Incident Template: Bug: Affected Monitors disappear

### ISSUE THREAD

**Issue by ThoSt81** [OneUptime/oneuptime#727]
**Describe the bug**
When creating a new template you can select one or multiple monitors that are affected. When you click next and then go back (click on the prev. step in the left panel) the selected monitors are not visible anymore. You can only see square boxes with 'x' to remove but not which monitor you selected.

**Expected behavior**
Selected monitors should be visible even when going back and forth in the template creations steps.

**Screenshots**
![grafik](https://github.com/OneUptime/oneuptime/assets/17260048/233fbb8c-2939-4ed8-b3c5-565a55e6f437)

**Comment by ThoSt81** [comment]
This actually also happens when creating a new incident. When you select one or multiple affected monitors, click next and then go back by clicking the prev. item in the left panel the monitors are gone.

**Comment by simlarsen** [comment]
Fixed: https://github.com/OneUptime/oneuptime/pull/728/commits/f5dab4379960dbe09ecde332f6458020765c6a00

Deploy by EOD today
