### ISSUE TITLE
Bug:  Cannot read properties of undefined (reading 'select')

### ISSUE THREAD

**Issue by teger** [OneUptime/oneuptime#732]
**Describe the bug**
I create a workflow with a component to send message to Mattermost.
With a Webhook trigger, no problem, the message send to Mattermost without problem !
Now, i replace the webhook trigger by a on create incident trigger.

When i create an incident, i have this message into workflow log !

Aug 23 2023, 17:15 GMT: Executing Component: incident-on-create-1
Aug 23 2023, 17:15 GMT: Cannot read properties of undefined (reading 'select')
<img width="667" alt="Capture d’écran 2023-08-23 à 19 45 37" src="https://github.com/OneUptime/oneuptime/assets/1482395/56999d6a-7a95-432f-b364-91ec1f0abbe1">
<img width="670" alt="Capture d’écran 2023-08-23 à 19 45 23" src="https://github.com/OneUptime/oneuptime/assets/1482395/53036808-69d4-42cb-bc78-b6cfa0dd7a8c">
<img width="1319" alt="Capture d’écran 2023-08-23 à 19 45 18" src="https://github.com/OneUptime/oneuptime/assets/1482395/d48144c9-44fa-4d8b-8e45-610b86d963f9">
<img width="1260" alt="Capture d’écran 2023-08-23 à 19 24 48" src="https://github.com/OneUptime/oneuptime/assets/1482395/e226c6a5-00b0-48c1-b2d8-97e7dd83b4d4">
<img width="1242" alt="Capture d’écran 2023-08-23 à 19 24 17" src="https://github.com/OneUptime/oneuptime/assets/1482395/d016d223-bf7f-4e79-9d41-761ce3c95b37">
<img width="1282" alt="Capture d’écran 2023-08-23 à 19 24 03" src="https://github.com/OneUptime/oneuptime/assets/1482395/ae03cc89-9434-4b1d-b546-f5f6e66d4c4c">

Thanks for your help

Best regards

**Comment by simlarsen** [comment]
You need to add json object to `Select` for on-create incident. 

Try: 

```
{
   "title": true
}

```

to select only incident title and add that JSON code to the select box of On Create Incident component.
