### ISSUE TITLE
Bug: SMS balance not found

### ISSUE THREAD

**Issue by teger** [OneUptime/oneuptime#733]
Hi,

i configure twilio in config.env.
In web application, add a phone number for SMS Notifications but i have an error on validation

 Your SMS balance is low. Please recharge your SMS balance in Project Settings > Notification Settings.

In notification settings, i enabled the SMS Notification.
But i don't find the balance option !

Thanks for your help

Best regards
<img width="498" alt="Capture d’écran 2023-08-23 à 19 58 25" src="https://github.com/OneUptime/oneuptime/assets/1482395/b1ecddf0-244c-44f4-b2ba-5c9259410700">
<img width="1689" alt="Capture d’écran 2023-08-23 à 19 57 03" src="https://github.com/OneUptime/oneuptime/assets/1482395/8dfad298-9187-49f7-ab2a-16977ef28d17">

**Comment by simlarsen** [comment]
Fixed: https://github.com/OneUptime/oneuptime/pull/734/commits/19f60de911188c6bfe863eb3e148bd704b3ef00e 

Will be released tomorrow. Ty for reporting.

**Comment by teger** [comment]
Hi,

After pull this version on branch release, i have the same problem !
<img width="1689" alt="Capture d’écran 2023-08-24 à 16 35 22" src="https://github.com/OneUptime/oneuptime/assets/1482395/8c58b9c5-a60e-4b1f-8b24-b768653ec1db">

And in the project settings >Notifications settings, i have no informations on the balance !
<img width="524" alt="Capture d’écran 2023-08-24 à 16 35 01" src="https://github.com/OneUptime/oneuptime/assets/1482395/b1ab495a-dbbb-43de-9911-52e1b2902235">


Thanks for your help
