### ISSUE TITLE
Enhancement: Monitoring port reachability

### ISSUE THREAD

**Issue by VA2XJM** [OneUptime/oneuptime#737]
**Is your feature request related to a problem? Please describe.**
Add a monitor type of "Port" that will validate if specified TCP port is reachable.

**Describe the solution you'd like**
System will try to connect to specified port to determine if it is reachable or not.

**Additional context**
Useful to monitor applications/containers without web GUI.

**Comment by simlarsen** [comment]
What do you mean, do a ping test?

**Comment by VA2XJM** [comment]
No, more like test if telnet port can be reached. So OneUptime open up a TCP request toward port 23 and if it can connect it is successful otherwise fail. (I give telnet as an exemple).

Pinging "server" will not tell if port 23 is reachable. It can be very useful in container monitoring.

**Comment by simlarsen** [comment]
@VA2XJM do you have a command line command that I can see.

**Comment by VA2XJM** [comment]
Easiest way is `nc -z -v -w5 <IP/HOST> <PORT>` -w specify the timeout in seconds.

Otherwise the `telnet` command can be used as a hack.

**Comment by ikalkov** [comment]
This would be actually pretty cool...

**Comment by MaxBroome** [comment]
agreed, Uptime Kuma has this feature. This is the one feature that hasn't made me switch yet.

**Comment by ikalkov** [comment]
Maybe to add some examples here: we offer TCP services which listen on specific ports (imagine VNC or SSH services). It is important for us to monitor them and make sure the service is responsive. Netcat is probably the easiest solution, but I am not a network expert.

**Comment by simlarsen** [comment]
This is complete. Will be launched end of today.
