### ISSUE TITLE
How does a custom probe and server communicate?

### ISSUE THREAD

**Issue by JesseWebDotCom** [OneUptime/oneuptime#738]
I need to test putting a probe behind a firewall. Specifically, how do they communicate (ex. via IP or name, port, protocol, direction, http method, etc) so I can open up the right ports? Thanks

**Comment by simlarsen** [comment]
They send REST requests (GET, POST, DELETE, etc) to `PROBE_API_URL`

`PROBE_API_URL` is the env var when you run custom probe. 

Docs: https://github.com/OneUptime/oneuptime/blob/master/Docs/Probe/CustomProbe.md

**Comment by simlarsen** [comment]
Feel free to re-open if you have any more questions.
