### ISSUE TITLE
SMS balance not found

### ISSUE THREAD

**Issue by teger** [OneUptime/oneuptime#740]
Hi,

After pull this version on branch release, i have the same problem !
<img width="1689" alt="Capture d’écran 2023-08-24 à 16 35 22" src="https://github.com/OneUptime/oneuptime/assets/1482395/8c58b9c5-a60e-4b1f-8b24-b768653ec1db">

And in the project settings >Notifications settings, i have no informations on the balance !
<img width="524" alt="Capture d’écran 2023-08-24 à 16 35 01" src="https://github.com/OneUptime/oneuptime/assets/1482395/b1ab495a-dbbb-43de-9911-52e1b2902235">

Thanks for your help

_Originally posted by @teger in https://github.com/OneUptime/oneuptime/issues/733#issuecomment-1691807662_

**Comment by simlarsen** [comment]
Looks like your app isnt being updated. We have added a way to check Version in the new version. When you sign in to dashboard. You should see "Version" beside "Legal" in the footer. Please click on it and let me know what your version is. 

If you dont see that link in Dashboard. You're not on latest. Please update OneUptime. 

I'll close this issue for now, if you still have issues - please re-open and I'll be happy to look into it.
