### ISSUE TITLE
Validation email

### ISSUE THREAD

**Issue by teger** [OneUptime/oneuptime#741]
Hi,

i am still face this issue, after re-pull and retstart the docker images.

My account is not validated again !!
<img width="739" alt="Capture d’écran 2023-08-24 à 22 55 47" src="https://github.com/OneUptime/oneuptime/assets/1482395/6fc689c8-a54e-4997-9575-5adda290a713">

Thank you for your help,

_Originally posted by @teger in https://github.com/OneUptime/oneuptime/issues/736#issuecomment-1692404774_

**Comment by simlarsen** [comment]
Looks like your app isnt being updated. We have added a way to check Version in the new version. When you sign in to dashboard. You should see "Version" beside "Legal" in the footer. Please click on it and let me know what your version is. 

If you dont see that link in Dashboard. You're not on latest. Please update OneUptime. 

I'll close this issue for now, if you still have issues - please re-open and I'll be happy to look into it.
