### ISSUE TITLE
Bug: UI - Wrong filter criteria is removed

### ISSUE THREAD

**Issue by VA2XJM** [OneUptime/oneuptime#742]
**Describe the bug**
When making a new `website` type monitor and removing the `Is Online` filter, the last line (`Response Status` by default) is remove.

**To Reproduce**
1. Add a new website monitor
2. In the criteria section, remove the `Is Online` filter condition
3. The `Is Online` remains while the `Response Status` is gone.

**Expected behavior**
The proper line should be removed.

**Screenshots**
![image](https://github.com/OneUptime/oneuptime/assets/13443249/2eaef4aa-86b0-4c54-ae88-c310268d59da)

![image](https://github.com/OneUptime/oneuptime/assets/13443249/5aaf90bb-9c61-47e0-b3e5-523556934535)

**Additional context**
oneuptime.com service

**Comment by simlarsen** [comment]
Fixed: https://github.com/OneUptime/oneuptime/commit/7aa90c1f2f1b51de4cfdb4f7470b9768e4a541a6 

Release EOD today
