### ISSUE TITLE
Bug: Update problem

### ISSUE THREAD

**Issue by teger** [OneUptime/oneuptime#743]
HI,

i pull the new version on release branch
From https://github.com/OneUptime/oneuptime
   b1bd44be59..6ca43a4c93  release          -> origin/release
 * [new tag]               7.0.657          -> 7.0.657
 * [new tag]               build-number-657 -> build-number-657
Updating b1bd44be59..6ca43a4c93
Fast-forward
 CommonServer/API/VersionAPI.ts             |   2 +-
 CommonServer/Config.ts                     |   1 -
 CommonUI/src/Components/Footer/Footer.tsx  |  15 ++++++++++++---
 Dashboard/src/Components/Footer/Footer.tsx | 119 ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++-----------
 Nginx/Dockerfile.tpl                       |   6 ++++++
 5 files changed, 127 insertions(+), 16 deletions(-)

Ok but, after startup with command line 
export $(grep -v '^#' config.env | xargs) && docker compose up --remove-orphans -d

Nothing in the footer ! No version
<img width="1700" alt="Capture d’écran 2023-08-25 à 13 48 28" src="https://github.com/OneUptime/oneuptime/assets/1482395/fda63d9e-61cd-4c36-b44b-9a375c8479b7">

Is there a cache that should be empty?
I have the impression that it does update data from git but that Docker loads old versions!

What command can I pass to make sure it loads the latest versions of files?

Thanks in advance

**Comment by teger** [comment]
and also, the legal link is incirrect. I load a 404 on oneuptime.com !
https://oneuptime.com/legal

**Comment by simlarsen** [comment]
Whats your APP_TAG in config.env. Is should be set to `release`

**Comment by simlarsen** [comment]
`export $(grep -v '^#' config.env | xargs) && docker compose pull`

Please run this to fetch newer images

**Comment by simlarsen** [comment]
Legal has been fixed here: https://github.com/OneUptime/oneuptime/commit/25669abb4085f16b2e08bc2f0017b6097f0b4457 

Deploy EOD today. Ty for reporting.
