### ISSUE TITLE
Enhancement: Footer in the table

### ISSUE THREAD

**Issue by teger** [OneUptime/oneuptime#744]
Hi, on the tables, by example, the table monitors, could it be possible to select the number of rows to display ?
And also, show the number of pages of this table !

view image attached
<img width="1412" alt="Capture d’écran 2023-08-25 à 13 57 47" src="https://github.com/OneUptime/oneuptime/assets/1482395/95c3cbf5-552c-4e29-8656-441f8edbdddc">

Thanks in advance

**Comment by simlarsen** [comment]
Yes, click on a button between next and previous buttons.

**Comment by simlarsen** [comment]
Made it simpler and added this icon: 

<img width="273" alt="image" src="https://github.com/OneUptime/oneuptime/assets/104437376/eb7a8ad2-efcf-4b50-b9ae-e17d5d314f4e">
