### ISSUE TITLE
Bug: SMS

### ISSUE THREAD

**Issue by teger** [OneUptime/oneuptime#745]
Hi,

Ok now, i can enter a phone number for the SMS Notification !
I configured twilio in config.env with the SID ands token keys

But i don't receive the validation code by SMS
Nothing in twilio log on twilio.com

are there logs on oneuptime to see if there is a problem sending SMS?

Thanks by advance,

**Comment by simlarsen** [comment]
Did you check SMS Logs page in project settings. What does it say?

**Comment by teger** [comment]
Hi,

In SMS Log : 

The 'To' number 06XXXXXX78 is not a valid phone number.
The 'To' number +3306XXXXXX78 is not a valid phone number.
The 'To' number +336XXXXXX78 is not a valid phone number.

Thanks in advance

**Comment by simlarsen** [comment]
Looks like those errors are from Twilio. You can check logs from the docker container called `notifications`

**Comment by teger** [comment]
ok, i logged on notification docker image

docker exec -it oneuptime-notification bash

But where is the file i must read please for thses errors ?

Thanks in advance,

**Comment by simlarsen** [comment]
Please run `docker compose logs notifications`

**Comment by teger** [comment]
Ok thanks

{
oneuptime-notification-1  |   message: 'Request ID: 849647b0-XXXXX-11ee-XXXX-5fe80d5fa7b4 -- POD NAME: NONE -- METHOD: POST -- URL: /sms/send\n' +
oneuptime-notification-1  |     ' Request ID: 849647b0-XXX-11ee-XXXX-5fe80d5fa7b4 -- Request Body: {\n' +
oneuptime-notification-1  |     '  "to": "06XXXXXX78",\n' +
oneuptime-notification-1  |     '  "message": "This message is from OneUptime. Your verification code is 167933",\n' +
oneuptime-notification-1  |     '  "isSensitive": true\n' +
oneuptime-notification-1  |     '}',
oneuptime-notification-1  |   level: 'info',
oneuptime-notification-1  |   timestamp: '2023-08-25T14:05:59.595Z'
oneuptime-notification-1  | }
oneuptime-notification-1  | {
oneuptime-notification-1  |   message: 'Response ID: 849647b0-XXXX-11ee-XXXX-5fe80d5fa7b4 -- POD NAME: NONE -- METHOD: POST -- URL: https://send -- DURATION: 491ms -- STATUS: 200\n' +
oneuptime-notification-1  |     ' Response ID: 849647b0-XXXX-11ee-XXXX-5fe80d5fa7b4 -- RESPONSE BODY: EMPTY',
oneuptime-notification-1  |   level: 'info',
oneuptime-notification-1  |   timestamp: '2023-08-25T14:06:00.086Z'
oneuptime-notification-1  | }

The url is weird ! https://send ??
I have no other messages in the logs !


Thanks by advance
