### ISSUE TITLE
Finding text in website monitors

### ISSUE THREAD

**Issue by JesseWebDotCom** [OneUptime/oneuptime#747]
For example, how would I create a monitor to know if "Copilot" is having an issue as listed on this page:
https://www.githubstatus.com

The Response Body | Contains is not enough to target a specific area of a web page.

**Comment by JesseWebDotCom** [comment]
As an alternative way for the specific example above, I probably could create a OneUptime heartbeat monitor and use the githubstatus subscription web hook notification - then use a workflow to parse the notification for "Incident with Copilot" and contains/does not contain "This incident has been resolved". Seems like a lot of work and a lot to go wrong.

**Comment by simlarsen** [comment]
@JesseWebDotCom how do you envision it to work in ideal scenerio?

**Comment by JesseWebDotCom** [comment]
Not sure on the ideal scenario (I'm no user interface designer) but maybe to create a monitor, select filter = response body, and then select a "Contains (Regex)", and then I specify a regex query in the text field.

**Comment by simlarsen** [comment]
@JesseWebDotCom and can I have a sample regex query for that github page so I understand it better.

**Comment by JesseWebDotCom** [comment]
Allow entering a query like this:
```
<span class="name">\s*Copilot\s*<\/span>\s*<span.*?><\/span>\s*<span.*?><\/span>\s*<span class="status-msg">(.*)<\/span>
```

to see if it equals "Normal"

**Comment by JesseWebDotCom** [comment]
Maybe even allow the queries to be named and reusable - example: I can call that query the Github Copilot Status Query and then select it in a dropdown to check if it equals normal to set the monitor to operational, see if it equals degraded to set the monitor to degraded, etc

**Comment by simlarsen** [comment]
@JesseWebDotCom Let me speak to my broader engineering team and think of a way and get back to you with some ideas by Wed. It's a long weekend here in UK, so will get back to you by Wed.

**Comment by simlarsen** [comment]
@JesseWebDotCom Nawaz has reached out to you a couple of times regarding some non-code work. Maybe his emails are going to your spam? Can you please revert to him so we can move that work async as we get the code part done.

**Comment by simlarsen** [comment]
@JesseWebDotCom FYI - He sent you some test emails.

**Comment by JesseWebDotCom** [comment]
Worked

**Comment by JesseWebDotCom** [comment]
Here's another scenario:
https://coder.com/docs/v2/latest/api/debug

The response is a single json for all services.  How would I setup 3 monitors of "health" for access_url, database, and web socket?

**Comment by simlarsen** [comment]
@JesseWebDotCom Got it! so, you basically want to parse json and see if its equal to some text. That should be simple to work on. 

currently working on admin dash. Once that is done, this will be the next thing I'll pick.

**Comment by JesseWebDotCom** [comment]
In this latest use case example, yes - parse json.  In others, its scrape / parse html (as the vendor does not provide json). If you want to break this into two issues, that's fine.

**Comment by simlarsen** [comment]
Got it! Created an issue: 

https://github.com/OneUptime/oneuptime/issues/761

**Comment by simlarsen** [comment]
I'll work on https://github.com/OneUptime/oneuptime/issues/761 next and then will circle back to this.

**Comment by simlarsen** [comment]
This is also done. Here are the docs: https://github.com/OneUptime/oneuptime/blob/master/Docs/Monitor/JavaScriptExpression.md

Release by end of the day tomorrow.
