### ISSUE TITLE
Bug: severity and state on create or on update incident

### ISSUE THREAD

**Issue by teger** [OneUptime/oneuptime#748]
Hi,

On on create or on update incident, i want tp read the severity or state of this incident.

<img width="726" alt="Capture d’écran 2023-08-25 à 22 31 35" src="https://github.com/OneUptime/oneuptime/assets/1482395/1d63652e-4c4f-448d-a9fb-71efe4e59638">
<img width="753" alt="Capture d’écran 2023-08-25 à 22 31 27" src="https://github.com/OneUptime/oneuptime/assets/1482395/6c24af9e-1a03-4e4a-baf4-ddff8e36b6fb">

In my post to Mattermost, i have this configuration
{
  "channel": "monitoring",
  "username": "monit",
  "text": "@channel [**{{local.components.incident-on-create-1.returnValues.model.description}} **](https://monit.nouveauxterritoires.com/dashboard/{{local.components.incident-on-create-1.returnValues.model.projectId.value}}/incidents/{{local.components.incident-on-create-1.returnValues.model._id}}) \n State : {{local.components.incident-on-create-1.returnValues.model.currentIncidentStateId.name}}  \n Severity : {{local.components.incident-on-create-1.returnValues.model.incidentSeverity.name}}"
}

But State and Severity are undefined always !
How to you configure these entities to show the name ?

Thnaks for your help,

**Comment by simlarsen** [comment]
In Select you can add: 

```
{
    .... 
   "incidentSeverity": { "name": true }
}
```
