### ISSUE TITLE
Bug: Send SMS

### ISSUE THREAD

**Issue by teger** [OneUptime/oneuptime#749]
Hi,

My SMS are not sent.
With docker compose log notification

I found this error : 

{
oneuptime-notification-1  |   message: 'Response ID: 606d7230-xxxxxx-11ee-xxxxxxx-3593e55d26fb -- POD NAME: NONE -- METHOD: POST -- URL: https://send -- DURATION: 341ms -- STATUS: 200\n' +
oneuptime-notification-1  |     ' Response ID: 606d7230-xxxxxx-11ee-xxxxxxx-3593e55d26fb -- RESPONSE BODY: EMPTY',
oneuptime-notification-1  |   level: 'info',
oneuptime-notification-1  |   timestamp: '2023-08-25T20:53:00.584Z'
oneuptime-notification-1  | }
oneuptime-notification-1  | {
oneuptime-notification-1  |   message: 'Response ID: 606ed1c0-xxxxxxx-11ee-xxxxxx-3593e55d26fb -- POD NAME: NONE -- METHOD: POST -- URL: https://send -- DURATION: 337ms -- STATUS: 200\n' +
oneuptime-notification-1  |     ' Response ID: 606ed1c0-xxxxxx-11ee-xxxxxx-3593e55d26fb -- RESPONSE BODY: EMPTY',
oneuptime-notification-1  |   level: 'info',
oneuptime-notification-1  |   timestamp: '2023-08-25T20:53:00.589Z'
oneuptime-notification-1  | 
}

The url https://send is correct ? 
I don't understand this error with twilio.

Thanks for your help

**Comment by teger** [comment]
Hi,

Ok i have more error logs in notifications
But i don't understand this error : 

{
oneuptime-notification-1  |   message: "The 'To' number 062XXXXXXX is not a valid phone number.",
oneuptime-notification-1  |   level: 'error',
oneuptime-notification-1  |   timestamp: '2023-08-31T14:25:27.163Z'
oneuptime-notification-1  | }


{
oneuptime-notification-1  |   message: "The 'To' number +33062XXXXXXX is not a valid phone number.",
oneuptime-notification-1  |   level: 'error',
oneuptime-notification-1  |   timestamp: '2023-08-31T14:25:27.163Z'
oneuptime-notification-1  | }

{
oneuptime-notification-1  |   message: "The 'To' number +33062XXXXXX is not a valid phone number.",
oneuptime-notification-1  |   level: 'error',
oneuptime-notification-1  |   timestamp: '2023-08-31T14:25:27.163Z'
oneuptime-notification-1  | }


what is the correct format for this phone number please ?

Thanks for your help

**Comment by simlarsen** [comment]
I'm afraid that error is not generated by OneUptime but by Twilio. Can you please ask their support for help? 

I'm closing this issue now since its not OneUptime related. If you need more help - Please let me know!
