### ISSUE TITLE
Bug: Unable to access through invitation link.

### ISSUE THREAD

**Issue by tarunkamra** [OneUptime/oneuptime#769]
I send myself (another email) the invitation link to test if I can be added to the Team Owners . I am already logged in via registered email (project owner).

This is the free edition I am talking.

1. Go to 'Project Settings'
2. Click on 'Teams and Members' in the Nav.
3. Click on 'View Team' in front of 'Owners' Team.
4. Click on 'Invite Team Member' to add . Fill in the details of the member to invite.
5. I see a confirmation that the invitation is being sent.
6. I see an email which says I am being invited.
7. I click on the link to find that I cannot access 

**Expected behavior**
I should have gotten access.

**Screenshots**
<img width="1143" alt="Screenshot 2023-09-2
![MicrosoftTeams-image (11)](https://github.com/OneUptime/oneuptime/assets/97393775/394aece1-b07e-48ae-8226-9f9119a54dbe)
0 at 11 45 50 AM" src="https://github.com/OneUptime/oneuptime/assets/97393775/a5282977-b67e-4acc-9c60-874ab3da2f92">

![MicrosoftTeams-image (11)](https://github.com/OneUptime/oneuptime/assets/97393775/96a52d76-1d44-4319-bbc9-f963fe878bba)

User-Agent:
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36

**Comment by simlarsen** [comment]
This is resolved. Please log out and log bck in.

**Comment by simlarsen** [comment]
or update if you're using local version of OneUptime.
