### ISSUE TITLE
Bug: Monitor remains permanently disabled if you delete an active incident before resolving it

### ISSUE THREAD

**Issue by angrygreenfrogs** [OneUptime/oneuptime#772]
**Describe the bug**
If you delete an incident before resolving it, the related monitor will remain disabled with the message "This monitor is disabled - We are not monitoring this monitor since it is disabled because of an active incident. To enable active monitoring, please resolve the incident." and seemingly no way to resolve the problem.

**To Reproduce**
1. Create a "Website" monitor
2. Manually create an incident (I chose "Critical")
3. Select the monitor as being affected with status to Degraded
4. Delete the incident without resolving it
5. Open the monitor again and notice the above error

**Expected behavior**
Deleting an incident should be equivalent to resolving it/undoing the effects from having an active incident.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Chrome
 - Version 116.0.5845.188

**Additional context**
N/A

**Comment by simlarsen** [comment]
Ty for reporting. This should be fixed tomorrow.

**Comment by simlarsen** [comment]
Fixed: https://github.com/OneUptime/oneuptime/commit/c6e5d642b5d3595f539a8b06fb5326dcdad4ec15 

Will be deployed to SaaS end of today.

**Comment by angrygreenfrogs** [comment]
Thank you, that sure was quick - I'll be glad to help re-test once it's deployed

**Comment by simlarsen** [comment]
@angrygreenfrogs deployed! 

If you like our work. We would really apprecdiate if you can post a review here: https://www.g2.com/products/oneuptime/reviews

**Comment by angrygreenfrogs** [comment]
@simlarsen Thanks, Simon. Just re-tested the exact use-case again, and can already confirm that fix did the trick - problem resolved.

I'm still doing a bunch of testing, etc, myself - I'll be glad to leave a review in the near future. I'd also be happy to provide some direct user feedback to your team once I get through everything.
