### ISSUE TITLE
Enhancement: On call rotation based on timezones 

### ISSUE THREAD

**Issue by simlarsen** [OneUptime/oneuptime#776]
Enable on call rotation based on timezones

**Comment by angrygreenfrogs** [comment]
Upvote from me - being able to control escalations with some type of time based control is probably the #1 thing I see missing from the system at the moment.

I'll mention it may be worth taking a look at https://github.com/target/goalert - they have a very simple/streamlined on-call system that allows you to create schedules and rotations, which works perfectly for use cases like where you have a US team and a Brazil team and you want to switch between them every day.

Create a set of rotations
![image](https://github.com/OneUptime/oneuptime/assets/413723/12aaa544-9b30-47a4-917e-a76eea5d6579)

Assign users to a rotation
![image](https://github.com/OneUptime/oneuptime/assets/413723/00047d93-281f-47c5-a15d-0d8feb83c2ee)

Create a schedule
![image](https://github.com/OneUptime/oneuptime/assets/413723/c50a66d7-8f60-4232-bc62-d793b82bcd77)

....etc...

I could even give you an account in my demo copy of it that I'm running for fun if you wanted to check it out.

**Comment by simlarsen** [comment]
This is done and will be launched today!
