### ISSUE TITLE
Bug: User invitation email doesn't properly encode email addresses in invite URL

### ISSUE THREAD

**Issue by angrygreenfrogs** [OneUptime/oneuptime#783]
**Describe the bug**
The invitation link in the user invitation email isn't URL encoding the user's email address

**To Reproduce**
1. Invite a user with a + in their email, like I tested with angrygreenfrogs+1@gmail.com
2. Receive the email
![image](https://github.com/OneUptime/oneuptime/assets/413723/c57c6f43-52ca-4e95-9bf6-c01cc53d1c33)
3. Notice the URL is https://oneuptime.com/accounts/register?email=angrygreenfrogs+1@gmail.com
4. That's incorrect, the "+" isn't encoded
5. Notice if you try to follow the link you end up stuck like this:
![image](https://github.com/OneUptime/oneuptime/assets/413723/e3880901-92cf-4302-9cd7-285f099cd03d)

**Expected behavior**
A properly encoded URL link would instead look like this:
https://oneuptime.com/accounts/register?email=angrygreenfrogs%2B1%40gmail.com

**Screenshots**
See above

**Comment by simlarsen** [comment]
Fixed: Will be deployed today: https://github.com/OneUptime/oneuptime/commit/41c6898d30e7130b376956cb2318a3024b2fee03
