### ISSUE TITLE
Enhancement: Consolidate Website and API monitors

### ISSUE THREAD

**Issue by JesseWebDotCom** [OneUptime/oneuptime#804]
Since the only difference between them is the request type and headers, I recommend combining them to one monitor type (Website / API).  Then just put request type into the advanced section and default to a get.

Here's another example where consolidation helps - Lets say you have a few website monitors (all working fine) but the website will soon require a header token for authentication.  You'd have to delete all existing website monitors, create api monitors, re-add them to status pages, etc.

**Comment by simlarsen** [comment]
We will expand Website and API monitors with more options in the future and they wil diverge. An example would be to do a lighthouse scan to make sure your website is compliant. 

Ideally if a page returns HTML use website monitor, otherwise use API.
