### ISSUE TITLE
Bug: Profile Icon on Dashboard is Static

### ISSUE THREAD

**Issue by kashalls** [OneUptime/oneuptime#809]
**Describe the bug**
The profile icon on the top right of the dashboard does not update if a profile picture is uploaded. It currently always shows a gray avatar which seems to be a static avatar.

**To Reproduce**

**Expected behavior**
This should only be shown if a profile picture hasn't been added, and when configured it should show image

**Screenshots**
![MDXs0G](https://github.com/OneUptime/oneuptime/assets/17620516/3d6daa49-9228-46e3-b173-23b90214b109)

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Windows 11
 - Browser [e.g. chrome, safari] Firefox

**Comment by simlarsen** [comment]
Fixed:https://github.com/OneUptime/oneuptime/commit/ff9117ab0597a4274f4e76d7ae44554a8719c924
