### ISSUE TITLE
Enhancement: New monitor type -> Group

### ISSUE THREAD

**Issue by JesseWebDotCom** [OneUptime/oneuptime#815]
Brainstormed with Nawaz on this one:

Add the ability to have a monitor which is just a group of other monitors

ex.
- there is a new monitor type called "Group"
- you can add monitors in the filters section (ex. I can I have one filters that check is a monitor is down while another checks if a monitor is up) 

This is critical is enabling bubbled up status pages at a management and even company level.

Ex. A facilities team may several monitors for the building but management might only need a few of them (ex. power, ac/heat). Adding this feature allows facilities to create a monitor group, add a management label to it to which management can consume in their status page.

**Comment by simlarsen** [comment]
This is done and released!
