### ISSUE TITLE
Bug: I have to pay my free plan

### ISSUE THREAD

**Issue by JanRajnoha** [OneUptime/oneuptime#821]
**Describe the bug**
I could not work with my account, because it need pay invoice, but I have free plan (from beginning).

**Expected behavior**
I won't be charged

**Screenshots**
![image](https://github.com/OneUptime/oneuptime/assets/16069721/3a6e0d68-14cd-499e-88dc-210a3c265f37)
![image](https://github.com/OneUptime/oneuptime/assets/16069721/e75d0378-f93d-437e-a5b5-89ba4e8a1838)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser Edge]

**Comment by simlarsen** [comment]
This is not a bug. Active monitors are paid on free plan. Please check pricing page for more details.

**Comment by JanRajnoha** [comment]
Okay, understand, so why I've been charged after 3 free months
