### ISSUE TITLE
Bug: Verification mail has not been sent

### ISSUE THREAD

**Issue by JanRajnoha** [OneUptime/oneuptime#825]
**Describe the bug**
Verification mail has not been sent. I'm using Outlook and earlier has not been problem with it. Currently I could not login or create new user.

**To Reproduce**
1. Create user using @outlook.com mail
2. Wait for verification mail

**Expected behavior**
Verification mail will arrive

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser Edge
 - Version Canary

**Additional context**
Would be great, if will be support for resending verification email

**Comment by simlarsen** [comment]
Is this on SaaS?

**Comment by JanRajnoha** [comment]
Yeah, via web, not my own

**Comment by simlarsen** [comment]
We have created a support request with outlook team. Will let you know when this is resolved.

**Comment by JanRajnoha** [comment]
thank you for info

**Comment by simlarsen** [comment]
This is fixed!
