### ISSUE TITLE
Enhancement: Allow custom clusterDomain instead of hardcoding cluster.local 

### ISSUE THREAD

**Issue by InputObject2** [OneUptime/oneuptime#828]
**Is your feature request related to a problem? Please describe.**
In the [environment variables](https://github.com/OneUptime/helm-chart/blob/master/oneuptime/templates/_helpers.tpl#L27-L57) (and in some other places), the chart hardcodes the cluster domain. This will prevent the chart from working on clusters that have a custom cluster domain name set.

**Describe the solution you'd like**
This could be set with a default value of cluster.local (which is currently the one that's set), which can then be overriden like in the redis or postgresql charts.

```yaml
clusterDomain: cluster.local
```

**Describe alternatives you've considered**
Another option is that since everything is in the same namespace, the addresses of all the different services could be simply referring to those services by name without needing the fully qualified domain name for each.

```yaml
- name: SERVER_DASHBOARD_API_HOSTNAME
  value: {{ $.Release.Name }}-dashboard-api.{{ $.Release.Namespace }}.svc.cluster.local
```
could be instead set as:

```yaml
- name: SERVER_DASHBOARD_API_HOSTNAME
  value: {{ $.Release.Name }}-dashboard-api
```

**Comment by simlarsen** [comment]
Fixed: https://github.com/OneUptime/oneuptime/commit/008e0c50b1bf2d57b8f0b97d9d7330cc44203439
