### ISSUE TITLE
Enhancement: Duplicate monitor should start disabled

### ISSUE THREAD

**Issue by JesseWebDotCom** [OneUptime/oneuptime#920]
The new duplicate monitor feature should not immediately start a monitor after duplication (since all you are allowed to change is the name before the duplicated monitor is immediately started).

**Comment by JesseWebDotCom** [comment]
Ideally it would allow you to also edit the description and then open the criteria page so you can edit things before the new monitor starts.

**Comment by simlarsen** [comment]
Added disabled option: https://github.com/OneUptime/oneuptime/commit/80b2474b036b09bda83f578e469a364072eb67d5 Will be released in few days.
