### ISSUE TITLE
Custom domain - cannot load certificate

### ISSUE THREAD

**Issue by Semetra22** [OneUptime/oneuptime#955]
**Describe the bug**
Added custom domain for statuspage. After verification the statuspage ist not reachable via custom domain 502 Bad Gateway.

**To Reproduce**
1. Added custom domain 
2. verified custom domain via txt entry
3. Added CNAME for statuspage
4. waited for cname to become active
5. when opening the domain a 502 Bad Gateway error is shown

Log-File states:
```
[error] 43#43: *1660 cannot load certificate "/etc/nginx/certs/StatusPageCerts/.crt": BIO_new_file() failed (SSL: error:80000002:system library::No such file or directory:calling fopen(/etc/nginx/certs/StatusPageCerts/.crt, r) error:10000080:BIO routines::no such file) while SSL handshaking
```

**Expected behavior**
Statuspage should be reachable via custom domain and presented as expected. 

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Chrome
 - Version: 119.0.6045.160

**Additional context**

**Comment by simlarsen** [comment]
is this self hosted?

**Comment by Semetra22** [comment]
@simlarsen yes, its a self hosted environment.

**Comment by Semetra22** [comment]
Test Environment is set up on docker.
More information following.

**Comment by Semetra22** [comment]
It worked out of nowhere at some point. Now we have reinstalled the service on a new cluster and unfortunately have the same problem again.

The domain has been made unrecognizable here:
The log shows: 
```
app-1 | body: 'StatusPageCerts:AddCerts - Checking CNAME status.mydomain.com',
app-1 | body: 'Failed checking for CNAME status.mydomain.com',
app-1 | body: 'StatusPageCerts:AddCerts - CNAME for status.mydomain.com is invalid. Removing cert',
```
When I use an online test tool to check the Cname entry, I get the correct CNAME record back.

Type | Domain Name | Canonical Name | TTL | Test | Result
CNAME | status.mydomain.com | oneuptime.myotherdomain.com | 24 hrs | DNS Record Published | DNS Record found

Would it be possible to simply create a self-signed certificate? The server is behind an Nginx reverse proxy anyway, which provides an SSL certificate. When I redirect to the http port I get the message "too many redirects".  So I think that the ingress service is expecting an https request.
