### ISSUE TITLE
Bug: Double window opening on image selection

### ISSUE THREAD

**Issue by richardfoleher** [OneUptime/oneuptime#956]
**Describe the bug**
When adding an image to the header for a status page, clicking add opens up 2 selection windows.

**To Reproduce**
1. Go to Status Pages - View Status Page - Header
2. Click on Edit Images in Logo, Cover and Favicon
3. Click on Upload Logo link
4. 2 slect image windows appear

**Expected behavior**
Only 1 image selection window

**screen recording**

https://github.com/OneUptime/oneuptime/assets/50485516/062d8065-4bc3-437e-86fc-d3f28067d997

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser Chrome
 - Version 119.0.6045.160 Official

**Comment by junedkhatri31** [comment]
@simlarsen I can work on this.

**Comment by simlarsen** [comment]
@junedkhatri31 feel free.
