### ISSUE TITLE
Bug: Workflow Sideover (drawer) panel content is hidden when overflow and cannot scroll.

### ISSUE THREAD

**Issue by soknaly** [OneUptime/oneuptime#962]
**Describe the bug**
The workflow sideover (drawer) panel content is hidden and cannot scroll down when the content is too long (overflow).

**To Reproduce**
1. Go to 'Workflow - View workflow - Builder'
2. Click on 'Run Workflow Manually or select the existing workflow component'
3. The drawer panel will open
4. Cannot scroll down the content to see more options.

**Expected behavior**
A panel content should be able to scroll down when the content is too long (overflow).

**Screenshots**

https://github.com/OneUptime/oneuptime/assets/20983608/a6ed1032-9ee1-45d8-b7fa-47491f79b02e

**Desktop (please complete the following information):**
 - OS: macOS Sonoma
 - Browser: Chrome
 - Version: 119.0.6045.159

**Comment by soknaly** [comment]
@simlarsen I can work on this one. But how do you want the header and footer of the drawer to behave? Should we update the Header and the Footer to be sticky approriately?

**Comment by simlarsen** [comment]
@soknaly we can make it sticky
